// Project: Git Architecture Diagram | Browser tests: Make Any Product with Genius AI — the home mission, the labeled
// ESP32 example (diagrams, editing, validation, Development Pack), project import, and a full idea → design run against a
// fake Genius Engineering Engine and a fake provider. No network: the real server serves the page, and every outside
// request goes to the fakes below.
import test from 'node:test'; import assert from 'node:assert/strict';
import { readFileSync, writeFileSync, mkdtempSync, rmSync } from 'node:fs'; import { tmpdir } from 'node:os'; import { join } from 'node:path';
import { chromium } from 'playwright';
import { unzipSync, strFromU8 } from 'fflate';
import '../support/no-autostart.mjs';
import { createAppServer } from '../../server.mjs';

const example = JSON.parse(readFileSync('public/assets/engineering/example-esp32.json', 'utf8'));
const ENGINE = 'https://engine.example'; const ENGINE_TOKEN = 'engine-browser-token-0123456789abcdef-012345'; const KEY = 'sk-fake-browser-visitor-key-placeholder-000000';
const generated = () => { const project = structuredClone(example); project.provenance = { ...project.provenance, example: false, provider: 'openai', model: 'gpt-test', engineVersion: '0.1.0', generatedAt: '2026-10-10T12:00:00.000Z' }; return project; };
const engineCalls = []; const providerCalls = [];
const network = async (url, init = {}) => {
  const target = String(url); const body = init.body ? JSON.parse(init.body) : {};
  if (target.startsWith(ENGINE)) {
    engineCalls.push({ path: new URL(target).pathname, raw: init.body || '' });
    if (target.endsWith('/v1/validate')) return Response.json({ done: true, project: body.project, validation: body.project.validation });
    if (target.endsWith('/v1/start')) return Response.json({ done: false, state: `${body.stage}-1`, generation: { name: { clarify: 'genius_engineering_clarify', design: 'genius_engineering_architecture', regenerate: 'genius_engineering_regenerate' }[body.stage], instructions: 'Fake engine step.', payload: { stage: body.stage }, schema: { type: 'object', properties: { ok: { type: 'boolean' } }, required: ['ok'], additionalProperties: false }, maxTokens: 2000 } });
    const project = generated();
    if (body.state === 'clarify-1') { project.artifacts = []; project.diagrams = []; project.validation = null; }
    if (body.state === 'regenerate-1') project.artifacts.find(item => item.path === 'firmware/include/config.h').content += '\n// Regenerated by the fake engine.\n';
    return Response.json({ done: true, project, validation: project.validation });
  }
  if (target.startsWith('https://api.openai.com/')) { if (new URL(target).pathname === '/v1/responses') providerCalls.push({ auth: init.headers?.Authorization || '' }); else return Response.json({ data: [] }); /* Model discovery from API settings is not a generation call. */ return Response.json({ status: 'completed', model: 'gpt-test', output: [{ content: [{ type: 'output_text', text: '{"ok":true}' }] }] }); }
  return new Response('{}', { status: 404 });
};
for (const name of ['GENIUS_ENGINE_URL', 'GENIUS_ENGINE_TOKEN']) delete process.env[name];
const server = createAppServer({ fetchImpl: network });
let base; let browser; const errors = []; const dir = mkdtempSync(join(tmpdir(), 'gad-idea-'));
test.before(async () => { await new Promise(resolve => server.listen(0, '127.0.0.1', resolve)); base = `http://127.0.0.1:${server.address().port}`; browser = await chromium.launch(); });
test.after(async () => { await browser?.close(); server.close(); rmSync(dir, { recursive: true, force: true }); for (const name of ['GENIUS_ENGINE_URL', 'GENIUS_ENGINE_TOKEN']) delete process.env[name]; });
async function open(path, { viewport = { width: 1440, height: 940 }, theme = 'dark' } = {}) {
  const context = await browser.newContext({ viewport, acceptDownloads: true }); const page = await context.newPage(); page.on('pageerror', error => errors.push(error.message));
  await page.addInitScript(value => { try { localStorage.setItem('gad-theme', value); } catch { /* Default theme. */ } }, theme);
  await page.goto(base + path); return page;
}
const noOverflow = page => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1);

test('the home page leads with the mission and keeps the GitHub import as the second path', async () => {
  const page = await open('/'); await page.waitForSelector('#welcome:not([hidden])');
  assert.equal(await page.title(), 'Make Any Product with Genius AI | Git Architecture Diagram');
  assert.equal((await page.textContent('#mission-title')).trim(), 'Make Any Product with Genius AI');
  assert.equal((await page.textContent('.mission-tagline')).trim(), 'Imagine It. Design It. Develop It. Validate It.');
  assert.deepEqual(await page.$$eval('.mission-card strong', nodes => nodes.map(node => node.textContent)), ['Start from an Idea', 'Import GitHub Project']);
  assert.deepEqual(await page.$$eval('.mission-outputs li', nodes => nodes.map(node => node.textContent.trim())), ['Validation Reports', 'Engineering Files', 'System Diagrams']);
  assert.ok(await page.locator('#hero-slot .command-bar').isVisible(), 'the GitHub input is still on the home page');
  assert.ok(await page.locator('.address-swap').isVisible()); assert.equal(await page.locator('#starter-examples').count(), 1);
  await page.click('#mission-import');
  await page.waitForFunction(() => document.activeElement?.id === 'repository');
  assert.equal(new URL(page.url()).pathname, '/');
  await page.click('#mission-idea'); await page.waitForSelector('#idea-view:not([hidden])');
  assert.equal(new URL(page.url()).pathname, '/new');
  assert.ok(await page.locator('#welcome').isHidden()); assert.ok(await page.locator('.command-bar').isHidden(), 'the idea workspace has its own form');
  await page.waitForFunction(() => /not connected/.test(document.querySelector('#idea-engine').textContent));
  assert.equal(await page.title(), 'Start from an Idea · Make Any Product with Genius AI');
  await page.goBack(); await page.waitForSelector('#welcome:not([hidden])'); assert.ok(await page.locator('.command-bar').isVisible());
  for (const width of [390, 430, 768, 1280]) { await page.setViewportSize({ width, height: 900 }); assert.ok(await noOverflow(page), `home: no horizontal overflow at ${width}px`); }
  await page.context().close();
});

test('without an engine, starting from an idea explains why and offers the labeled example', async () => {
  const page = await open('/new'); await page.waitForFunction(() => /not connected/.test(document.querySelector('#idea-engine').textContent));
  await page.fill('#idea-text', 'An ESP32 weather station that posts readings over Wi-Fi.'); await page.click('#idea-run');
  await page.waitForSelector('#idea-progress.error:not([hidden])'); assert.match(await page.textContent('#idea-progress'), /not connected on this site yet/);
  assert.equal(engineCalls.length, 0); assert.equal(providerCalls.length, 0);
  await page.context().close();
});

test('the ESP32 example: labeled, diagrams parsed in the browser, editable files, honest validation, and a Development Pack', async () => {
  const page = await open('/new'); await page.waitForSelector('#idea-view:not([hidden])');
  await page.click('#idea-example'); await page.waitForSelector('#idea-project:not([hidden])');
  assert.match(await page.textContent('#idea-banner'), /Example project — prepared by Pro_Amine LLC/);
  assert.equal(await page.textContent('#idea-project-title'), example.title);
  assert.deepEqual(await page.$$eval('#idea-tabs .idea-tab', nodes => nodes.map(node => node.textContent)), ['Overview', 'Requirements', 'Architecture', 'Files', 'Validation', 'Development Pack']);
  assert.match(await page.textContent('#idea-panel'), /Prepared example; no AI model was used/);

  await page.click('.idea-tab[data-tab=requirements]'); assert.ok((await page.locator('#idea-panel .idea-table-wrap').count()) >= 3);
  assert.ok(await page.locator('#idea-panel h3', { hasText: 'Assumptions' }).count()); assert.ok(await page.locator('#idea-panel h3', { hasText: 'Verification plan' }).count());
  await page.click('.idea-tab[data-tab=architecture]');
  await page.waitForFunction(count => document.querySelectorAll('#idea-panel .idea-diagram-canvas svg').length === count, example.diagrams.length + 1, { timeout: 20000 });
  assert.equal(await page.locator('#idea-panel .idea-badge', { hasText: 'Mermaid syntax checked in your browser' }).count(), example.diagrams.length + 1);
  assert.ok(await page.locator('#idea-panel h3', { hasText: 'Pin map' }).count());

  await page.click('.idea-tab[data-tab=validation]');
  const summary = await page.$$eval('#idea-panel .idea-stat strong', nodes => nodes.map(node => Number(node.textContent)));
  assert.deepEqual(summary, [example.validation.summary.pass, example.validation.summary.warn, example.validation.summary.fail, example.validation.summary.notRun]);
  assert.match(await page.textContent('#idea-panel .idea-note'), /never counted as a pass/);
  assert.ok(await page.locator('#idea-panel .idea-badge', { hasText: 'Not run' }).count() >= 1);

  await page.click('.idea-tab[data-tab=files]');
  await page.click('.idea-file[data-file] >> text=firmware/include/config.h');
  const editor = page.locator('.idea-code-editor'); await editor.click(); await page.keyboard.press('End'); await page.keyboard.type(' // edited in the browser');
  await page.waitForSelector('.idea-editor-head .idea-badge.tone-warn'); assert.equal(await page.textContent('.idea-editor-head .idea-badge.tone-warn'), 'Edited — not re-validated');
  await page.getByRole('button', { name: 'Re-validate', exact: true }).click(); await page.waitForSelector('#idea-progress.error:not([hidden])'); assert.match(await page.textContent('#idea-progress'), /Re-validation runs in the Genius Engineering Engine/);
  await page.click('.idea-tab[data-tab=validation]'); assert.match(await page.textContent('#idea-panel'), /Files changed since this report/);

  await page.click('.idea-tab[data-tab=pack]');
  const [zip] = await Promise.all([page.waitForEvent('download'), page.click('text=Download Development Pack (.zip)')]);
  assert.match(zip.suggestedFilename(), /-development-pack\.zip$/);
  const entries = unzipSync(readFileSync(await zip.path())); const names = Object.keys(entries); const folder = names[0].split('/')[0];
  for (const path of [...example.artifacts.map(item => item.path), '.genius-project/project.json', '.genius-project/OVERVIEW.md', '.genius-project/VALIDATION_REPORT.md', '.genius-project/diagrams/dependencies.mmd']) assert.ok(entries[`${folder}/${path}`], path);
  assert.match(strFromU8(entries[`${folder}/firmware/include/config.h`]), /edited in the browser/, 'the pack carries the edits');
  assert.equal(JSON.parse(strFromU8(entries[`${folder}/.genius-project/project.json`])).artifacts.find(item => item.path === 'firmware/include/config.h').status, 'edited');
  const [json] = await Promise.all([page.waitForEvent('download'), page.click('text=Export project file (.json)')]);
  const exported = join(dir, 'exported.json'); writeFileSync(exported, readFileSync(await json.path()));
  await page.context().close();

  // The exported file opens again in a new tab; a file that is not a project is refused with a reason.
  const again = await open('/new'); await again.waitForSelector('#idea-view:not([hidden])');
  await again.setInputFiles('#idea-file', exported); await again.waitForSelector('#idea-project:not([hidden])');
  assert.equal(await again.textContent('#idea-project-title'), example.title);
  const broken = join(dir, 'broken.json'); writeFileSync(broken, JSON.stringify({ schema: 'gad.project/1', title: 'Bad', requirements: [], components: [], artifacts: [{ path: '../escape.txt', content: '' }] }));
  await again.setInputFiles('#idea-file', broken); await again.waitForSelector('#idea-progress.error:not([hidden])'); assert.match(await again.textContent('#idea-progress'), /Unsafe file path/);
  await again.setViewportSize({ width: 390, height: 860 }); await again.click('.idea-tab[data-tab=files]'); assert.ok(await noOverflow(again), 'idea workspace: no horizontal overflow on a phone');
  await again.context().close();
});

test('with an engine: idea → questions → design → regenerate, and the key reaches only the provider', async () => {
  process.env.GENIUS_ENGINE_URL = ENGINE; process.env.GENIUS_ENGINE_TOKEN = ENGINE_TOKEN; engineCalls.length = 0; providerCalls.length = 0;
  try {
    const page = await open('/new'); await page.waitForFunction(() => document.querySelector('#idea-engine').classList.contains('connected'));
    await page.fill('#idea-text', 'An ESP32 development board with USB-C, a BME280 sensor, and a status LED.'); await page.click('#idea-run');
    await page.waitForSelector('#idea-progress.error:not([hidden])'); assert.match(await page.textContent('#idea-progress'), /API settings/); // No key yet: nothing is sent.
    assert.equal(engineCalls.length, 0);
    await page.selectOption('#provider', 'openai'); await page.fill('#api-key', KEY); await page.click('#settings .dialog-actions .primary-button');
    await page.click('#idea-run'); await page.waitForSelector('#idea-questions:not([hidden])');
    assert.equal(await page.locator('#idea-question-list input').count(), example.questions.length);
    await page.fill('#idea-question-list input >> nth=0', 'Yes, USB-C only');
    await page.click('#idea-design'); await page.waitForSelector('#idea-project:not([hidden])');
    assert.ok(await page.locator('#idea-banner').isHidden(), 'a generated project carries no example label');
    assert.match(await page.textContent('#idea-panel'), /Generated by openai gpt-test through the Genius Engineering Engine 0\.1\.0/);
    await page.click('.idea-tab[data-tab=files]'); await page.click('.idea-file[data-file] >> text=firmware/include/config.h');
    await page.fill('.idea-instruction', 'Add a comment'); await page.click('text=Regenerate this file');
    await page.waitForFunction(() => /Regenerated by the fake engine/.test(document.querySelector('.idea-code-editor').value));
    await page.getByRole('button', { name: 'Re-validate', exact: true }).click(); await page.waitForFunction(() => /Validation report updated/.test(document.querySelector('#toast').textContent));
    assert.deepEqual(engineCalls.map(call => call.path), ['/v1/start', '/v1/resume', '/v1/start', '/v1/resume', '/v1/start', '/v1/resume', '/v1/validate']);
    assert.ok(engineCalls.every(call => !call.raw.includes(KEY)), 'the engine never receives the visitor key');
    assert.equal(providerCalls.length, 3); assert.ok(providerCalls.every(call => call.auth === `Bearer ${KEY}`));
    await page.context().close();
  } finally { delete process.env.GENIUS_ENGINE_URL; delete process.env.GENIUS_ENGINE_TOKEN; }
});

test('both themes render the mission, and no page script errors occurred', async () => {
  const light = await open('/', { theme: 'light' }); await light.waitForSelector('#welcome:not([hidden])');
  const colors = await light.$eval('.mission-card', card => ({ text: getComputedStyle(card).color, background: getComputedStyle(document.body).backgroundColor }));
  assert.notEqual(colors.text, colors.background); await light.context().close();
  assert.deepEqual(errors, []);
});
