// Copyright © 2026 Pro_Amine LLC
// Created & Developed by Amine Saoud ibn al-Bashir
// Git Architecture Diagram · SPDX-License-Identifier: MIT · Provenance ID: GAD-PROVENANCE-CORE-001
// Project: Git Architecture Diagram | Component: HTTP server | Author: Amine Saoud ibn al-Bashir.
// Features: same-origin API, streamed progress, bundled browser modules, bounded analysis, and secure defaults.
import http from 'node:http'; // Serve the application without an additional web framework.
import { readFile, readdir } from 'node:fs/promises'; // Read allowlisted static assets and the release files for /api/version.
import path from 'node:path'; // Resolve static files within fixed roots.
import { fileURLToPath } from 'node:url'; // Resolve the application directory independently of the working directory.
import { AppError, VERSION } from './src/github.mjs'; // Reuse user-facing HTTP errors and the release identifier.
import { runAnalysis, getSession, publicAIStatus } from './src/service.mjs'; // Expose the same analysis pipeline used by the CLI.
import { searchEvidence } from './src/genius.mjs';
import { askGenius } from './src/ask.mjs';
import { extractRepository, validateExtractInput, EXTRACT_LIMITS } from './src/extract.mjs'; // Full-repository extract from one archive. // Grounded, opt-in answers to repository questions. // Provide source-backed questions without an AI dependency.
const ROOT = path.dirname(fileURLToPath(import.meta.url)); const rates = new Map(); let active = 0; // Scope assets and bound process-level resource usage.
const MIME = { '.html': 'text/html; charset=utf-8', '.css': 'text/css; charset=utf-8', '.js': 'text/javascript; charset=utf-8', '.mjs': 'text/javascript; charset=utf-8', '.svg': 'image/svg+xml', '.json': 'application/json', '.woff2': 'font/woff2', '.png': 'image/png', '.webp': 'image/webp', '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg', '.ico': 'image/x-icon' }; // Define static content types explicitly.
import { PROVIDERS, resolveCredentials } from './src/providers.mjs'; // Describe the same authorized provider catalog as the analysis service.
import { discoverModels, testConnection } from './src/model-registry.mjs'; // Two recommended models per provider and the connection test.
import { runGeniusAgent } from './src/genius-agent.mjs'; // One Deep Genius agent call per request.
import { ProviderError } from './src/provider-errors.mjs'; // Classified provider failures carry a stable kind for the interface.
import { versionInfo, sourceDigest, SOURCE_PATTERN, cleanCommit } from './src/provenance.mjs'; // Public provenance and a non-secret build fingerprint.
const CSP = "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; font-src 'self' data:; connect-src 'self'; worker-src 'self' blob:; object-src 'none'; base-uri 'none'; frame-ancestors 'none'"; // Keep repository content from loading arbitrary scripts or remote assets.
function json(response, status, data) { response.writeHead(status, { 'Content-Type': 'application/json', 'Cache-Control': 'no-store' }); response.end(JSON.stringify(data)); } // Return compact uncached API responses.
async function body(request, limit = 20000) { let text = ''; for await (const chunk of request) { text += chunk; if (Buffer.byteLength(text) > limit) throw new AppError(413, 'The request is too large.'); } try { return JSON.parse(text); } catch { throw new AppError(400, 'Expected a JSON request.'); } } // Bound and parse incoming JSON.
async function gitHead() { // The deployed commit when the host keeps .git; never required.
  try { const head = (await readFile(path.join(ROOT, '.git', 'HEAD'), 'utf8')).trim(); if (!head.startsWith('ref: ')) return cleanCommit(head); const ref = head.slice(5); if (!/^refs\/[\w./-]+$/.test(ref) || ref.includes('..')) return null; // Only follow a plain branch reference inside .git.
    try { return cleanCommit(await readFile(path.join(ROOT, '.git', ref), 'utf8')); } catch { const packed = await readFile(path.join(ROOT, '.git', 'packed-refs'), 'utf8'); return cleanCommit(packed.split('\n').find(line => line.endsWith(` ${ref}`))?.split(' ')[0]); } } catch { return null; }
} // End commit lookup.
let version = null; // Computed once per process: the release files do not change while it runs.
async function buildVersion() { const files = []; for (const dir of ['', 'src', 'public']) for (const name of await readdir(path.join(ROOT, dir))) { const relative = dir ? `${dir}/${name}` : name; if (SOURCE_PATTERN.test(relative)) files.push([relative, await readFile(path.join(ROOT, relative))]); } return versionInfo({ commit: cleanCommit(process.env.GAD_COMMIT || process.env.SOURCE_COMMIT || process.env.GIT_COMMIT) || await gitHead(), digest: await sourceDigest(files), runtime: 'node' }); } // Digest of the shipped source, recomputable with npm run provenance.
function diagnose(result) { if (!process.env.NODE_TEST_CONTEXT) console.info('[provider-test]', JSON.stringify(result.diagnostics)); return result; } // Log safe connection diagnostics only: provider, model, key presence and length, hosts, HTTP statuses, classification.
const LIMITS = { agent: 90, default: 20 }; // Requests per client address per minute; a Deep Genius run makes up to 25 short agent calls.
function guard(request, bucket = 'default') { // Validate browser origin and request frequency. There is no instance password: the public site needs none.
  const expectedOrigin = process.env.PUBLIC_ORIGIN || `http://${request.headers.host}`; if (request.headers.origin && request.headers.origin !== expectedOrigin) throw new AppError(403, 'This API accepts same-origin requests only.'); // Prevent cross-origin use of local credentials.
  const now = Date.now(); const ip = `${request.socket.remoteAddress || 'unknown'}|${bucket}`; const current = rates.get(ip); if (rates.size > 5000) rates.clear(); // Bound the in-memory limiter.
  const item = current && current.until > now ? current : { count: 0, until: now + 60000 }; item.count++; rates.set(ip, item); if (item.count > (LIMITS[bucket] || LIMITS.default)) throw new AppError(429, 'Too many requests. Please wait a minute.'); // Limit expensive endpoint calls per direct client address.
} // End API request admission.
async function staticAsset(url, response, method) { // Serve only public files and explicitly approved dependency distributions.
  let base = path.join(ROOT, 'public'); let relative = url.pathname.slice(1); // Default to the application public directory.
  const vendors = { '/vendor/mermaid/': 'mermaid/dist', '/vendor/dompurify/': 'dompurify/dist', '/vendor/marked/': 'marked/lib', '/vendor/fflate/': 'fflate/esm' }; // Restrict browser dependencies to known distribution roots.
  const vendor = Object.keys(vendors).find(prefix => url.pathname.startsWith(prefix)); // Detect an approved browser-module URL.
  if (url.pathname === '/shared/evidence.mjs') { base = path.join(ROOT, 'src'); relative = 'evidence.mjs'; } // Serve the single portable browser search module from an explicit allowlist.
  else if (vendor) { base = path.join(ROOT, 'node_modules', vendors[vendor]); relative = url.pathname.slice(vendor.length); } // Resolve dependency assets under their distribution directory.
  const appRoute = !vendor && url.pathname !== '/shared/evidence.mjs' && (relative === '' || /^(examples|browse)\/?$/.test(relative) || /^[\w.-]+\/[\w.-]+(?:\/.*)?$/.test(relative)); // Any /owner/repo/... path opens the workspace, which explains unsupported GitHub pages.
  if (relative === '') relative = 'index.html';
  try { relative = decodeURIComponent(relative); } catch { throw new AppError(400, 'Invalid asset path.'); } // Decode once before containment checking.
  const file = path.resolve(base, relative); if (!file.startsWith(base + path.sep) || relative.includes('\\') || (!MIME[path.extname(file)] && !appRoute)) throw new AppError(404, 'Asset not found.'); if (!MIME[path.extname(file)]) { const page = await readFile(path.join(ROOT, 'public', 'index.html')); response.writeHead(200, { 'Content-Type': MIME['.html'], 'Cache-Control': 'no-cache' }); response.end(method === 'HEAD' ? undefined : page); return; } // Prevent arbitrary filesystem reads and directory listing.
  let data; try { data = await readFile(file); } catch { if (!appRoute || relative.startsWith('assets/')) throw new AppError(404, 'Asset not found.'); data = await readFile(path.join(ROOT, 'public', 'index.html')); response.writeHead(200, { 'Content-Type': MIME['.html'], 'Cache-Control': 'no-cache' }); response.end(method === 'HEAD' ? undefined : data); return; } // Real files win; otherwise repository paths get the workspace.
  response.writeHead(200, { 'Content-Type': MIME[path.extname(file)], 'Cache-Control': vendor || relative.startsWith('assets/') ? 'public, max-age=86400' : 'no-cache' }); response.end(method === 'HEAD' ? undefined : data); // Cache immutable installed dependencies more aggressively than application files.
} // End static asset serving.
export function createAppServer({ fetchImpl = fetch } = {}) { // Export the actual server; tests may inject a GitHub/provider transport.
  return http.createServer(async (request, response) => { // Handle the small application API and its frontend.
    response.setHeader('Content-Security-Policy', CSP); response.setHeader('X-Content-Type-Options', 'nosniff'); response.setHeader('Referrer-Policy', 'no-referrer'); response.setHeader('Permissions-Policy', 'camera=(), microphone=(), geolocation=()'); // Apply browser protections before every response.
    try { // Convert all request failures into bounded user-facing errors.
      const url = new URL(request.url, 'http://localhost'); // Parse routing independently of an untrusted Host header.
      if (url.pathname === '/api/health' && request.method === 'GET') return json(response, 200, { ok: true, version: VERSION, limits: { extract: EXTRACT_LIMITS.node,  maxFiles: 120 }, providers: Object.keys(PROVIDERS), publicAI: publicAIStatus(process.env) }); // Expose capability state without secrets.
      if (url.pathname === '/api/version' && request.method === 'GET') return json(response, 200, await (version ??= buildVersion())); // Public provenance: project, version, commit, source digest, fingerprint. No secrets.
      if (url.pathname.startsWith('/api/')) { // Admit only the documented same-origin API operations.
        if (request.method !== 'POST') throw new AppError(405, 'Use POST for this API endpoint.'); guard(request, url.pathname === '/api/genius/agent' ? 'agent' : 'default'); // Require bounded authenticated browser actions where configured.
        if (!String(request.headers['content-type'] || '').startsWith('application/json')) throw new AppError(415, 'Use application/json.'); const input = await body(request, url.pathname === '/api/genius/agent' ? 200000 : url.pathname === '/api/ask' ? 64000 : 20000); if (input && typeof input === 'object') delete input.githubToken; // Reject cross-site form submissions and oversized bodies. The browser never supplies GitHub credentials; only the optional server GITHUB_TOKEN is used, for public repositories.
        if (url.pathname === '/api/extract') { validateExtractInput(input); if (active >= 3) throw new AppError(429, 'The server is busy. Please try again shortly.'); active++; const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), 180000); response.on('close', () => { if (!response.writableEnded) controller.abort(); }); response.writeHead(200, { 'Content-Type': 'application/x-ndjson', 'Cache-Control': 'no-store', 'X-Accel-Buffering': 'no' }); const emit = data => { if (!response.destroyed) response.write(JSON.stringify(data) + '\n'); }; try { const result = await extractRepository(input, { signal: controller.signal, progress: event => emit({ type: 'progress', ...event }), fetchImpl, runtime: 'node' }); emit({ type: 'result', result }); } catch (error) { emit({ type: 'error', message: error instanceof AppError ? error.message : 'The extract failed unexpectedly. Please try again.', status: error.status || 500 }); } finally { active--; clearTimeout(timer); response.end(); } return; } // Stream archive progress, then the extract.
        if (url.pathname === '/api/models') { const { provider, apiKey } = resolveCredentials(input); const controller = new AbortController(); response.on('close', () => { if (!response.writableEnded) controller.abort(); }); return json(response, 200, await discoverModels(provider, apiKey, { fetchImpl, signal: controller.signal })); } // Two recommended models, refreshed from the provider's official list when a key is supplied.
        if (url.pathname === '/api/provider/test') { const { provider, apiKey, model } = resolveCredentials(input); const controller = new AbortController(); response.on('close', () => { if (!response.writableEnded) controller.abort(); }); return json(response, 200, diagnose(await testConnection(provider, { apiKey, model, fetchImpl, signal: controller.signal }))); } // Two independent checks: the model list and one tiny structured request.
        if (url.pathname === '/api/genius/agent') { const { provider, apiKey, model } = resolveCredentials(input); const controller = new AbortController(); response.on('close', () => { if (!response.writableEnded) controller.abort(); }); return json(response, 200, await runGeniusAgent(input, { provider, apiKey, model, fetchImpl, signal: controller.signal, cache: true })); } // Deep Genius: one allowlisted agent per request; the browser orchestrates and verifies.
        if (url.pathname === '/api/ask' && input.ai === true) { const { provider, apiKey, model } = resolveCredentials(input); const controller = new AbortController(); response.on('close', () => { if (!response.writableEnded) controller.abort(); }); return json(response, 200, await askGenius(input, { apiKey, model, provider, signal: controller.signal, fetchImpl })); } // Answer from browser-held excerpts with the key entered in this tab.
        if (url.pathname === '/api/ask') { const result = getSession(input.id); const question = String(input.question || '').slice(0, 600); return json(response, 200, { mode: 'evidence-search', matches: searchEvidence(result, question), explanation: 'These are matching lines from the files Genius actually read. They are source evidence, not a generated answer.' }); } // Keep the no-model question mode truthful.
        if (url.pathname !== '/api/analyze') throw new AppError(404, 'API endpoint not found.'); // Reject undocumented operations.
        if (active >= 3) throw new AppError(429, 'The analyzer is busy. Please try again shortly.'); active++; // Bound concurrent GitHub and model work.
        const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), 180000); response.on('close', () => { if (!response.writableEnded) controller.abort(); }); // Cancel work when the browser leaves or the run deadline expires.
        response.writeHead(200, { 'Content-Type': 'application/x-ndjson', 'Cache-Control': 'no-store', 'X-Accel-Buffering': 'no' }); // Stream progress without buffering it behind a proxy.
        const emit = data => { if (!response.destroyed) response.write(JSON.stringify(data) + '\n'); }; // Write one complete progress event per line.
        try { const result = await runAnalysis(input, { signal: controller.signal, progress: event => emit({ type: 'progress', ...event }), allowEnvAI: false, fetchImpl }); emit({ type: 'result', result }); } catch (error) { emit({ type: 'error', message: error instanceof AppError ? error.message : 'Analysis failed unexpectedly. Please try again.', status: error.status || 500 }); } finally { active--; clearTimeout(timer); response.end(); } // Preserve completion, error, and resource-release behavior.
        return; // Finish the streamed analysis response.
      } // End API routing.
      if (!['GET', 'HEAD'].includes(request.method)) throw new AppError(405, 'Method not allowed.'); await staticAsset(url, response, request.method); // Serve the regular browser application.
    } catch (error) { if (!response.headersSent) json(response, error.status || 500, { error: error instanceof AppError ? error.message : 'The request could not be completed.', ...(error instanceof ProviderError ? { kind: error.kind, retryable: error.retryable, suggestion: error.suggestion, providerStatus: error.providerStatus } : {}) }); else response.end(); } // Avoid exposing stack traces or credentials.
  }); // Return the configured server instance.
} // End application server construction.
let started = null; // Listen at most once per process, however the entry file is loaded.
export function startServer(env = process.env) { // Start the HTTP listener from HOST and PORT.
  if (started) return started; if (env.GENIUS_ACCESS_TOKEN) console.warn('GENIUS_ACCESS_TOKEN is set but no longer used: the instance password was removed in 1.1. Remove it from the hosting environment.'); // Name the variable, never its value.
  const host = env.HOST || '127.0.0.1'; const port = /^\d+$/.test(String(env.PORT ?? '').trim()) ? Number(env.PORT) : (env.PORT || 3000); // Accept a numeric port or a socket/pipe path supplied by a hosting runner.
  started = createAppServer(); const ready = () => console.log(`Git Architecture Diagram is running at ${typeof port === 'number' ? `http://${host}:${port}` : port}`); // Report the address the application requested.
  if (typeof port === 'number') started.listen(port, host, ready); else started.listen(port, ready); return started; // A runner such as LiteSpeed lsnode or Passenger may still rebind listen() to its own socket.
} // End listener startup.
// Hosting runners (Hostinger Node.js Web Apps via LiteSpeed lsnode, Passenger, PM2) load this entry file with require() or import() from their own script, so process.argv[1] is not this file. Start on load; tests opt out with GIT_ARCHITECTURE_DIAGRAM_AUTOSTART=0.
if (process.env.GIT_ARCHITECTURE_DIAGRAM_AUTOSTART !== '0') startServer();
