// Project: Git Architecture Diagram | Component: Hosted Worker | Author: Amine Saoud ibn al-Bashir.
import { timingSafeEqual } from 'node:crypto'; // Compare optional instance passwords without an ordinary string comparison.
import { Buffer } from 'node:buffer'; // Use an explicit Workers-compatible Node buffer import.
import { AppError, boundedJson, VERSION } from './src/github.mjs'; // Reuse the validated ingestion contracts and bounded JSON reader.
import { runAnalysis, readSource } from './src/service.mjs'; // Share verified analysis and source browsing with the local server.
import { runQuestion } from './src/question.mjs'; // Generate one explicitly requested, source-verified Genius answer.
import { PROVIDERS } from './src/providers.mjs'; // Describe the same authorized provider catalog as the analysis service.
const CSP = "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; font-src 'self' data:; connect-src 'self'; worker-src 'self' blob:; object-src 'none'; base-uri 'none'; frame-ancestors 'none'"; // Keep untrusted repository content inside the same rendering boundary as the local app.
const SECURITY = { 'Content-Security-Policy': CSP, 'X-Content-Type-Options': 'nosniff', 'Referrer-Policy': 'no-referrer', 'Permissions-Policy': 'camera=(), microphone=(), geolocation=()' }; // Apply the browser protections to hosted responses.
const HOSTED_FILES = 40; // Keep hosted analyses within a bounded upstream request budget.
function json(status, data) { return new Response(JSON.stringify(data), { status, headers: { ...SECURITY, 'Content-Type': 'application/json', 'Cache-Control': 'no-store' } }); } // Produce uncached API responses without leaking internal exceptions.
function authorized(request, env) { if (!env.GENIUS_ACCESS_TOKEN) return false; const expected = Buffer.from(env.GENIUS_ACCESS_TOKEN); const actual = Buffer.from(request.headers.get('X-Instance-Token') || ''); return expected.length === actual.length && timingSafeEqual(expected, actual); } // Require explicit instance access before using a hosted provider key.
export function createWorker({ analyze = runAnalysis, source = readSource, ask = runQuestion } = {}) { // Allow the actual Worker protocol to be tested with deterministic GitHub responses.
  const rates = new Map(); let active = 0; // Bound work per isolate without storing repository reports in a distributed session cache.
  return { async fetch(request, env = {}, ctx = {}) { // Handle both the public application and its streaming analysis endpoint.
    try { // Convert API and routing failures into clear browser messages.
      const url = new URL(request.url); // Read the incoming path independently of any repository input.
      if (url.pathname === '/api/health' && request.method === 'GET') return json(200, { ok: true, version: VERSION, runtime: 'worker', limits: { maxFiles: HOSTED_FILES }, aiAvailable: Boolean(env[PROVIDERS[env.GENIUS_PROVIDER || 'openai']?.keyEnv] && env.GENIUS_MODEL && env.GENIUS_ACCESS_TOKEN), accessRequired: Boolean(env.GENIUS_ACCESS_TOKEN) }); // Expose capabilities and budget limits without exposing keys.
      if (url.pathname.startsWith('/api/')) { // Admit only documented hosted analysis requests.
        if (request.method !== 'POST') throw new AppError(405, 'Use POST for analysis.'); const origin = request.headers.get('Origin'); const allowedOrigins = (env.PUBLIC_ORIGINS || env.PUBLIC_ORIGIN || url.origin).split(',').map(value => value.trim()).filter(Boolean); if (origin && !allowedOrigins.includes(origin)) throw new AppError(403, 'This API accepts same-origin requests only.'); // Admit only explicitly configured website origins, including an optional custom domain.
        if (env.GENIUS_ACCESS_TOKEN && !authorized(request, env)) throw new AppError(401, 'Enter the instance access password in Settings.'); // Preserve access controls on protected deployments.
        if (!(request.headers.get('Content-Type') || '').startsWith('application/json')) throw new AppError(415, 'Use application/json.'); if (Number(request.headers.get('Content-Length')) > 20000) throw new AppError(413, 'The request is too large.'); // Reject form submissions and clearly oversized requests early.
        const ip = request.headers.get('CF-Connecting-IP') || 'shared'; const now = Date.now(); for (const [key, value] of rates) if (value.until < now) rates.delete(key); if (rates.size >= 5000) rates.clear(); const rate = rates.get(ip) || { count: 0, until: now + 60000 }; rates.set(ip, rate); if (++rate.count > 20) throw new AppError(429, 'Too many requests. Please wait a minute.'); // Bound anonymous work without trusting arbitrary forwarded headers.
        if (!['/api/analyze', '/api/source', '/api/ask'].includes(url.pathname)) throw new AppError(404, 'Endpoint not found.'); let input; try { input = await boundedJson(request, 20000); } catch (error) { if (error.status === 502) throw new AppError(400, 'Expected a valid JSON request.'); throw error; } if (!input || typeof input !== 'object' || Array.isArray(input)) throw new AppError(400, 'Expected a repository request.'); // Distinguish malformed client JSON from upstream failures.
        if (url.pathname === '/api/source') { if (active >= 2) throw new AppError(429, 'The analyzer is busy. Please try again shortly.'); active++; try { return json(200, await source(input, { env, signal: AbortSignal.any([request.signal, AbortSignal.timeout(45000)]) })); } finally { active--; } } // Preview requested source with fresh access verification and no retained credentials.
        const question = url.pathname === '/api/ask'; const budget = Number(input.maxFiles ?? 32); if (!question && (!Number.isInteger(budget) || budget < 1 || budget > HOSTED_FILES)) throw new AppError(400, `Choose 1 to ${HOSTED_FILES} files on this hosted instance. Narrow the folder scope for deeper analysis.`); // Make the hosted budget explicit rather than silently claiming full coverage.
        if (active >= 2) throw new AppError(429, 'The analyzer is busy. Please try again shortly.'); active++; const controller = new AbortController(); const signal = AbortSignal.any([request.signal, controller.signal]); const timer = setTimeout(() => controller.abort(), 180000); const encoder = new TextEncoder(); let canceled = false; // Bound memory, lifetime, and concurrent requests.
        const stream = new ReadableStream({ start(output) { const emit = event => { if (!canceled) output.enqueue(encoder.encode(JSON.stringify(event) + '\n')); }; const task = (async () => { try { const result = await (question ? ask : analyze)(input, { env, signal, allowEnvAI: authorized(request, env), cachePublic: true, retainSession: false, maxGitHubRequests: question ? 12 : 48, progress: event => emit({ type: 'progress', ...event }) }); emit(question ? { type: 'answer', answer: result } : { type: 'result', result }); } catch (error) { emit({ type: 'error', message: signal.aborted ? 'Analysis canceled or timed out.' : error instanceof AppError ? error.message : 'Analysis failed unexpectedly. Please try again.', status: signal.aborted ? 408 : error.status || 500 }); } finally { clearTimeout(timer); active--; if (!canceled) output.close(); } })(); if (ctx.waitUntil) ctx.waitUntil(task); }, cancel() { canceled = true; controller.abort(); } }); // Reuse short-lived anonymous public evidence; exclude private and credential-specific reports.
        return new Response(stream, { headers: { ...SECURITY, 'Content-Type': 'application/x-ndjson', 'Cache-Control': 'no-store', 'X-Accel-Buffering': 'no' } }); // Return a live NDJSON stream the existing interface already understands.
      } // End hosted API routing.
      if (!['GET', 'HEAD'].includes(request.method)) throw new AppError(405, 'Method not allowed.'); if (!env.ASSETS?.fetch) throw new AppError(503, 'The website assets are not available.'); let asset = await env.ASSETS.fetch(request); // Serve only the packaged public assets through the platform binding.
      if (asset.status === 404 && (url.pathname === '/' || /^\/examples\/?$/.test(url.pathname) || /^\/[\w.-]+\/[\w.-]+(?:\/(?:tree|blob)\/.*)?\/?$/.test(url.pathname))) { const index = new URL('/index.html', url); asset = await env.ASSETS.fetch(new Request(index, { method: request.method })); } // Route repository, branch, and folder URLs to the same working workspace.
      const headers = new Headers(asset.headers); for (const [name, value] of Object.entries(SECURITY)) headers.set(name, value); return new Response(request.method === 'HEAD' ? null : asset.body, { status: asset.status, headers }); // Preserve asset types and status codes while adding security headers.
    } catch (error) { return json(error instanceof AppError ? error.status : 500, { error: error instanceof AppError ? error.message : 'The request could not be completed.' }); } // Avoid sending stack traces or provider credentials to clients.
  } }; // Return the Workers fetch handler required by the hosting platform.
} // End Worker construction.
export default createWorker(); // Register a default callable fetch handler in the built Worker.
