// Project: Git Architecture Diagram | Component: Hosted Worker | Author: Amine Saoud ibn al-Bashir.
import { AppError, boundedJson, VERSION } from './src/github.mjs'; // Reuse the validated ingestion contracts and bounded JSON reader.
import { runAnalysis, publicAIStatus } from './src/service.mjs'; // Run the same real source analyzer used by the local server and CLI.
import { PROVIDERS, resolveCredentials } from './src/providers.mjs';
import { discoverModels, testConnection } from './src/model-registry.mjs';
import { runGeniusAgent } from './src/genius-agent.mjs';
import { ProviderError } from './src/provider-errors.mjs';
import { askGenius } from './src/ask.mjs';
import { extractRepository, validateExtractInput, EXTRACT_LIMITS } from './src/extract.mjs'; // Full-repository extract from one archive. // Answer questions without retaining sessions. // Describe the same authorized provider catalog as the analysis service.
const CSP = "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; font-src 'self' data:; connect-src 'self'; worker-src 'self' blob:; object-src 'none'; base-uri 'none'; frame-ancestors 'none'"; // Keep untrusted repository content inside the same rendering boundary as the local app.
const SECURITY = { 'Content-Security-Policy': CSP, 'X-Content-Type-Options': 'nosniff', 'Referrer-Policy': 'no-referrer', 'Permissions-Policy': 'camera=(), microphone=(), geolocation=()' }; // Apply the browser protections to hosted responses.
const HOSTED_FILES = 40; // Keep hosted analyses within a bounded upstream request budget.
function json(status, data) { return new Response(JSON.stringify(data), { status, headers: { ...SECURITY, 'Content-Type': 'application/json', 'Cache-Control': 'no-store' } }); } // Produce uncached API responses without leaking internal exceptions.
function withoutGitHubToken(input) { if (input && typeof input === 'object') delete input.githubToken; return input; } // The browser never supplies GitHub credentials; only the optional server GITHUB_TOKEN is used, for public repositories.
function cacheStore() { // Persist public system maps in the platform cache when the runtime provides one.
  const cache = globalThis.caches?.default; if (!cache) return null;
  const url = key => `https://system-map.cache.invalid/${encodeURIComponent(key)}`;
  return { async get(key) { const hit = await cache.match(url(key)); return hit ? hit.json() : null; }, async put(key, value) { await cache.put(url(key), new Response(JSON.stringify(value), { headers: { 'Content-Type': 'application/json', 'Cache-Control': 'public, max-age=2592000' } })); } };
} // End cache store.
export function createWorker({ analyze = runAnalysis, ask = askGenius, extract = extractRepository, agent = runGeniusAgent, models = discoverModels, test = testConnection } = {}) { // Allow the actual Worker protocol to be tested with deterministic GitHub responses.
  const rates = new Map(); let active = 0; // Bound work per isolate without storing repository reports in a distributed session cache.
  return { async fetch(request, env = {}, ctx = {}) { // Handle both the public application and its streaming analysis endpoint.
    try { // Convert API and routing failures into clear browser messages.
      const url = new URL(request.url); // Read the incoming path independently of any repository input.
      if (url.pathname === '/api/health' && request.method === 'GET') return json(200, { ok: true, version: VERSION, runtime: 'worker', limits: { maxFiles: HOSTED_FILES, extract: EXTRACT_LIMITS.worker }, providers: Object.keys(PROVIDERS), publicAI: publicAIStatus(env) }); // Expose capabilities and budget limits without exposing keys.
      if (url.pathname.startsWith('/api/')) { // Admit only documented hosted analysis requests.
        if (request.method !== 'POST') throw new AppError(405, 'Use POST for analysis.'); const origin = request.headers.get('Origin'); const allowedOrigins = (env.PUBLIC_ORIGINS || env.PUBLIC_ORIGIN || url.origin).split(',').map(value => value.trim()).filter(Boolean); if (origin && !allowedOrigins.includes(origin)) throw new AppError(403, 'This API accepts same-origin requests only.'); // Admit only explicitly configured website origins, including an optional custom domain.
        if (!(request.headers.get('Content-Type') || '').startsWith('application/json')) throw new AppError(415, 'Use application/json.'); const bodyLimit = url.pathname === '/api/genius/agent' ? 200000 : url.pathname === '/api/ask' ? 64000 : 20000; if (Number(request.headers.get('Content-Length')) > bodyLimit) throw new AppError(413, 'The request is too large.'); // Reject form submissions and clearly oversized requests early.
        const ip = `${request.headers.get('CF-Connecting-IP') || 'shared'}|${url.pathname === '/api/genius/agent' ? 'agent' : 'default'}`; const now = Date.now(); for (const [key, value] of rates) if (value.until < now) rates.delete(key); if (rates.size >= 5000) rates.clear(); const rate = rates.get(ip) || { count: 0, until: now + 60000 }; rates.set(ip, rate); if (++rate.count > (url.pathname === '/api/genius/agent' ? 90 : 20)) throw new AppError(429, 'Too many requests. Please wait a minute.'); // Bound anonymous work without trusting arbitrary forwarded headers.
        if (url.pathname === '/api/extract') { let input; try { input = await boundedJson(request, 20000); } catch (error) { if (error.status === 502) throw new AppError(400, 'Expected a valid JSON request.'); throw error; } withoutGitHubToken(input); validateExtractInput(input); if (active >= 2) throw new AppError(429, 'The server is busy. Please try again shortly.'); active++; const controller = new AbortController(); const signal = AbortSignal.any([request.signal, controller.signal]); const timer = setTimeout(() => controller.abort(), 180000); const encoder = new TextEncoder(); let canceled = false; // Same admission rules as analysis.
          const stream = new ReadableStream({ start(output) { const emit = event => { if (!canceled) output.enqueue(encoder.encode(JSON.stringify(event) + '\n')); }; const task = (async () => { try { const result = await extract(input, { signal, runtime: 'worker', progress: event => emit({ type: 'progress', ...event }) }); emit({ type: 'result', result }); } catch (error) { emit({ type: 'error', message: error instanceof AppError ? error.message : 'The extract failed unexpectedly. Please try again.', status: error.status || 500 }); } finally { active--; clearTimeout(timer); if (!canceled) output.close(); } })(); ctx.waitUntil?.(task); }, cancel() { canceled = true; controller.abort(); } });
          return new Response(stream, { headers: { ...SECURITY, 'Content-Type': 'application/x-ndjson', 'Cache-Control': 'no-store', 'X-Accel-Buffering': 'no' } }); } // Stream archive progress, then the extract.
        if (['/api/models', '/api/provider/test', '/api/genius/agent'].includes(url.pathname)) { let input; try { input = await boundedJson(request, bodyLimit); } catch (error) { if (error.status === 502) throw new AppError(400, 'Expected a valid JSON request.'); throw error; } const { provider, apiKey, model } = resolveCredentials(input); // Same credential rules as the Node server: only the key entered in the browser tab.
          if (url.pathname === '/api/models') return json(200, await models(provider, apiKey, { signal: request.signal }));
          if (url.pathname === '/api/provider/test') return json(200, await test(provider, { apiKey, model, signal: request.signal }));
          return json(200, await agent(input, { provider, apiKey, model, signal: request.signal })); } // Deep Genius: one allowlisted agent per request.
        if (url.pathname === '/api/ask') { let question; try { question = await boundedJson(request, 64000); } catch (error) { if (error.status === 502) throw new AppError(400, 'Expected a valid JSON request.'); throw error; } if (question?.ai !== true) throw new AppError(400, 'Keyword search runs in your browser; send ai: true to ask a model.'); withoutGitHubToken(question); const { provider, apiKey, model } = resolveCredentials(question); return json(200, await ask(question, { apiKey, model, provider, signal: request.signal })); } // Stateless grounded answers from browser-held excerpts.
        if (url.pathname !== '/api/analyze') throw new AppError(404, 'Endpoint not found. Evidence search runs in your browser after analysis.'); let input; try { input = await boundedJson(request, 20000); } catch (error) { if (error.status === 502) throw new AppError(400, 'Expected a valid JSON request.'); throw error; } if (!input || typeof input !== 'object' || Array.isArray(input)) throw new AppError(400, 'Expected a repository analysis request.'); withoutGitHubToken(input); // Keep hosted search independent of server sessions and distinguish invalid client JSON from provider failures.
        const budget = Number(input.maxFiles ?? 32); if (!Number.isInteger(budget) || budget < 1 || budget > HOSTED_FILES) throw new AppError(400, `Choose 1 to ${HOSTED_FILES} files on this hosted instance. Narrow the folder scope for deeper analysis.`); // Make the hosted budget explicit rather than silently claiming full coverage.
        if (active >= 2) throw new AppError(429, 'The analyzer is busy. Please try again shortly.'); active++; const controller = new AbortController(); const signal = AbortSignal.any([request.signal, controller.signal]); const timer = setTimeout(() => controller.abort(), 180000); const encoder = new TextEncoder(); let canceled = false; // Bound memory, lifetime, and concurrent requests.
        const stream = new ReadableStream({ start(output) { const emit = event => { if (!canceled) output.enqueue(encoder.encode(JSON.stringify(event) + '\n')); }; const task = (async () => { try { const result = await analyze(input, { env, signal, allowEnvAI: false, cachePublic: false, retainSession: false, maxGitHubRequests: 48, aiStore: cacheStore(), progress: event => emit({ type: 'progress', ...event }) }); emit({ type: 'result', result }); } catch (error) { emit({ type: 'error', message: error instanceof AppError ? error.message : 'Analysis failed unexpectedly. Please try again.', status: error.status || 500 }); } finally { clearTimeout(timer); active--; if (!canceled) output.close(); } })(); if (ctx.waitUntil) ctx.waitUntil(task); }, cancel() { canceled = true; controller.abort(); } }); // Stream real progress while keeping private reports out of hosted process caches.
        return new Response(stream, { headers: { ...SECURITY, 'Content-Type': 'application/x-ndjson', 'Cache-Control': 'no-store', 'X-Accel-Buffering': 'no' } }); // Return a live NDJSON stream the existing interface already understands.
      } // End hosted API routing.
      if (!['GET', 'HEAD'].includes(request.method)) throw new AppError(405, 'Method not allowed.'); if (!env.ASSETS?.fetch) throw new AppError(503, 'The website assets are not available.'); let asset = await env.ASSETS.fetch(request); // Serve only the packaged public assets through the platform binding.
      if (asset.status === 404 && !url.pathname.startsWith('/assets/') && (url.pathname === '/' || /^\/(examples|browse)\/?$/.test(url.pathname) || /^\/[\w.-]+\/[\w.-]+(?:\/.*)?$/.test(url.pathname))) { const index = new URL('/index.html', url); asset = await env.ASSETS.fetch(new Request(index, { method: request.method })); } // Route repository, branch, and folder URLs to the same working workspace.
      const headers = new Headers(asset.headers); for (const [name, value] of Object.entries(SECURITY)) headers.set(name, value); return new Response(request.method === 'HEAD' ? null : asset.body, { status: asset.status, headers }); // Preserve asset types and status codes while adding security headers.
    } catch (error) { return json(error instanceof AppError ? error.status : 500, { error: error instanceof AppError ? error.message : 'The request could not be completed.', ...(error instanceof ProviderError ? { kind: error.kind, retryable: error.retryable, suggestion: error.suggestion, providerStatus: error.providerStatus } : {}) }); } // Avoid sending stack traces or provider credentials to clients.
  } }; // Return the Workers fetch handler required by the hosting platform.
} // End Worker construction.
export default createWorker(); // Register a default callable fetch handler in the built Worker.
