// Project: Git Architecture Diagram | Meaningful ingestion, evidence, and credential-boundary tests.
import test from 'node:test'; import assert from 'node:assert/strict'; // Use the Node test runner without a testing framework dependency.
import { AppError, parseRepository, normalizeScope, safeTextPath, GitHubReader, selectFiles, ingest, boundedJson } from '../src/github.mjs'; // Exercise actual ingestion code.
import { analyzeSnapshot, extractDependencies, guideMarkdown, searchEvidence } from '../src/genius.mjs'; // Exercise source-grounded reports.
import { aiContext, validateInterpretation, explainWithAI } from '../src/ai.mjs'; // Exercise the optional AI contract without spending provider credits.
import { runAnalysis, getSession } from '../src/service.mjs'; // Exercise cache isolation and the shared orchestration pipeline.
import { files, entries, commitSHA, githubFixture } from './fixtures.mjs'; // Reuse immutable source fixtures.
const snapshot = { owner: 'acme', repo: 'demo', fullName: 'acme/demo', htmlUrl: 'https://github.com/acme/demo', route: '/repos/acme/demo', sha: commitSHA, branch: 'main', scope: '', entries, description: 'Fixture project', private: false, treeTruncated: false }; // Represent a real-shaped analysis snapshot.
const coverage = { readFiles: files.length, eligibleFiles: files.length, listedFiles: files.length, maxFiles: 32, bytes: 200, treeTruncated: false, skipped: [], unsampledFiles: 0 }; // Provide complete fixture coverage.
test('GitHub transport preserves the native fetch receiver contract', async () => { const fixture = githubFixture({ name: 'native-fetch' }); function nativeFetch(...args) { if (this !== undefined && this !== globalThis) throw new TypeError('Illegal invocation: function called with incorrect this reference'); return fixture.fetchImpl(...args); } const result = await runAnalysis({ repository: 'acme/native-fetch', maxFiles: 2 }, { env: {}, fetchImpl: nativeFetch, cachePublic: false }); assert.equal(result.coverage.readFiles, 2); assert.equal(result.repository.sha, commitSHA); }); // Reproduce the Workers-only failure that ordinary Node fetch and arrow-function fixtures do not detect.
test('repository parsing accepts clone and scoped URLs, rejects arbitrary destinations', () => { assert.equal(parseRepository('https://github.com/acme/demo.git').fullName, 'acme/demo'); assert.deepEqual(parseRepository('https://github.com/acme/demo/tree/feature/ui/src').tail, ['feature', 'ui', 'src']); for (const input of ['https://evil.test/acme/demo', 'http://github.com/acme/demo', 'https://x:y@github.com/acme/demo', 'https://github.com:123/acme/demo', 'acme/demo/issues/1', '../demo']) assert.throws(() => parseRepository(input), AppError); assert.throws(() => normalizeScope('src/../secret')); }); // Verify user inputs cannot select an arbitrary outbound host.
test('tree URLs resolve slash-containing refs after GitHub 422 responses and pin the folder', async () => { const mock = githubFixture({ invalidRefStatus: 422 }); const reader = new GitHubReader({ fetchImpl: mock.fetchImpl }); const data = await reader.snapshot(parseRepository('acme/demo/tree/feature/ui/src')); assert.equal(data.sha, commitSHA); assert.equal(data.branch, 'feature/ui'); assert.equal(data.scope, 'src'); assert.ok(data.entries.every(item => item.path === 'src' || item.path.startsWith('src/'))); assert.ok(mock.requests.every(item => item.options.redirect === 'error')); }); // Test the ambiguous GitHub URL case end to end.
test('a server token cannot disclose a private repository without a caller token', async () => { const mock = githubFixture({ privateRepo: true }); const reader = new GitHubReader({ token: 'server-only-placeholder', fetchImpl: mock.fetchImpl }); await assert.rejects(reader.snapshot(parseRepository('acme/demo')), error => error.status === 403); assert.equal(mock.requests.length, 1); const allowed = await reader.snapshot(parseRepository('acme/demo'), { suppliedToken: true }); assert.equal(allowed.private, true); }); // Enforce the private-repository trust boundary before tree reads.
test('blob ingestion verifies Git identity and rejects altered content', async () => { const mock = githubFixture(); const reader = new GitHubReader({ fetchImpl: mock.fetchImpl }); const file = await reader.blob(snapshot, entries.find(item => item.path === 'src/main.js')); assert.equal(file.content, files.find(item => item.path === 'src/main.js').content); const altered = new GitHubReader({ fetchImpl: async () => Response.json({ encoding: 'base64', content: Buffer.from('altered').toString('base64') }) }); await assert.rejects(altered.blob(snapshot, entries.find(item => item.type === 'blob')), /integrity/); }); // Ensure reports cite the bytes identified by the commit.
test('selection excludes credential files, generated files, symlinks, and oversized text', () => { const unsafe = ['.env', 'config/secrets.json', 'keys/key.pem', 'node_modules/a.js', 'dist/b.js']; unsafe.forEach(item => assert.equal(safeTextPath(item), false)); const extended = { ...snapshot, entries: [...entries, ...unsafe.map(path => ({ path, type: 'blob', size: 10, mode: '100644' })), { path: 'link.js', type: 'blob', mode: '120000', size: 10 }, { path: 'huge.md', type: 'blob', size: 100000 }] }; const selected = selectFiles(extended, 120); assert.equal(selected.eligible, files.length); assert.equal(selectFiles(snapshot, 2).selected.length, 2); }); // Bound source exposure and work before fetching blobs.
test('rate-limited ingestion preserves partial evidence and accounts for skipped reads', async () => { let calls = 0; const reader = { blob: async (_, entry) => { if (++calls > 1) throw new AppError(429, 'Rate limit'); return files.find(file => file.path === entry.path); } }; const data = await ingest(snapshot, reader, 4); assert.equal(data.files.length, 1); assert.equal(data.coverage.skipped.length, 3); assert.equal(data.coverage.unsampledFiles, files.length - 1); }); // Verify partial results never imply full source coverage.
test('upstream JSON has a streaming byte limit', async () => { await assert.rejects(boundedJson(Response.json({ payload: 'x'.repeat(100) }), 20), error => error.status === 413); }); // Prevent unbounded upstream response retention.
test('dependency evidence resolves local code, skips comments, and keeps unresolved imports separate', () => { const input = [...files, { path: 'firmware/main.cpp', content: '#include "sensor.h"\n#include <Arduino.h>\n' }, { path: 'pkg/main.py', content: '# import unknown\nfrom .helper import run\n' }]; const listing = [...entries, { path: 'firmware/sensor.h', type: 'blob' }, { path: 'pkg/helper.py', type: 'blob' }]; const data = extractDependencies(input, listing); assert.equal(data.edges.length, 3); assert.deepEqual(data.edges.map(edge => edge.line), [2, 1, 2]); assert.equal(data.external.length, 1); assert.equal(data.external[0].specifier, 'Arduino.h'); }); // Check three implemented language families and stable evidence lines.
test('quoted examples and unrelated monorepo headers do not become dependency edges', () => { const input = [{ path: 'src/main.js', content: 'const example = "require(\'./helper.js\')";\nconst text = `\nimport value from "./helper.js";\n`;\n' }, { path: 'project/src/main.cpp', content: '#include "unrelated.h"\n' }]; const listing = [...entries, { path: 'another-project/include/unrelated.h', type: 'blob' }, { path: 'project/platformio.ini', type: 'blob' }]; const data = extractDependencies(input, listing); assert.equal(data.edges.length, 0); assert.deepEqual(data.external.map(item => item.specifier), ['unrelated.h']); }); // Guard against plausible but unsupported relationships across strings or independent projects.
test('Genius preserves authored diagrams and exports immutable citations with honest validation', () => { const result = analyzeSnapshot(snapshot, files, coverage); assert.equal(result.documented.length, 1); assert.equal(result.documented[0].basis, 'documentation'); assert.equal(result.dependencies.length, 1); const guide = guideMarkdown(result); assert.ok(guide.includes(`/blob/${commitSHA}/src/main.js#L2`)); assert.ok(guide.includes('Repository code was not executed or built')); assert.equal(searchEvidence(result, 'helper')[0].path, 'src/main.js'); }); // Verify source provenance across the web and downloadable guide.
test('AI validation removes invented paths and citations beyond supplied excerpts', () => { const result = analyzeSnapshot(snapshot, files, coverage); const { lineLimits } = aiContext(result); const raw = { overview: 'Explanation', components: [{ path: 'invented.js', description: 'Fake' }, { path: 'src/main.js', description: 'Entry candidate' }], relationships: [{ from: 'src/main.js', to: 'src/helper.js', description: 'Uses helper', evidencePath: 'src/main.js', evidenceLine: 2 }, { from: 'src/main.js', to: 'src/helper.js', description: 'Fake citation', evidencePath: 'src/main.js', evidenceLine: 9999 }], recommendations: [], limitations: [] }; const validated = validateInterpretation(raw, result, lineLimits); assert.equal(validated.components.length, 1); assert.equal(validated.relationships.length, 1); assert.equal(validated.discardedReferences, 2); assert.equal(validated.relationships[0].basis, 'ai'); }); // Reject invalid references without pretending to verify model semantics.
test('Responses integration sends bounded evidence, strict schema, and store=false', async () => { const result = analyzeSnapshot(snapshot, files, coverage); let sent; const report = { overview: 'Fixture overview', components: [], relationships: [], recommendations: [], limitations: ['Partial analysis'] }; const ai = await explainWithAI(result, { apiKey: 'test-placeholder', model: 'test-model', fetchImpl: async (url, options) => { sent = { url, ...JSON.parse(options.body) }; return Response.json({ model: 'test-model', output: [{ content: [{ type: 'output_text', text: JSON.stringify(report) }] }], usage: { input_tokens: 123 } }); } }); assert.equal(sent.url, 'https://api.openai.com/v1/responses'); assert.equal(sent.store, false); assert.equal(sent.text.format.strict, true); assert.ok(sent.instructions.includes('untrusted evidence')); assert.equal(ai.overview, report.overview); assert.equal(ai.usage.input_tokens, 123); }); // Verify provider request and response contracts without a live model call.
test('public cache reuses one commit but preserves the newly selected branch', async () => { const mock = githubFixture({ name: 'cache-test' }); const options = { env: {}, fetchImpl: mock.fetchImpl }; const first = await runAnalysis({ repository: 'acme/cache-test', maxFiles: 3 }, options); const blobCalls = mock.requests.filter(item => item.url.includes('/git/blobs/')).length; const second = await runAnalysis({ repository: 'acme/cache-test', ref: 'feature/ui', maxFiles: 3 }, options); assert.equal(first.cacheHit, false); assert.equal(second.cacheHit, true); assert.equal(second.repository.branch, 'feature/ui'); assert.equal(mock.requests.filter(item => item.url.includes('/git/blobs/')).length, blobCalls); assert.equal(getSession(second.id).id, second.id); }); // Test cache correctness under two refs pointing to the same commit.
test('private results never enter the shared cache and reports omit credentials', async () => { const mock = githubFixture({ privateRepo: true, name: 'private-test' }); const input = { repository: 'acme/private-test', githubToken: 'private-test-placeholder', maxFiles: 2 }; const first = await runAnalysis(input, { env: {}, fetchImpl: mock.fetchImpl }); const second = await runAnalysis(input, { env: {}, fetchImpl: mock.fetchImpl }); assert.equal(first.cacheHit, false); assert.equal(second.cacheHit, false); assert.equal(JSON.stringify(second).includes(input.githubToken), false); }); // Verify private-cache isolation and absence of serialized secrets.
test('an unapproved environment AI key is not used by web requests', async () => { const mock = githubFixture({ name: 'no-ai-test' }); const result = await runAnalysis({ repository: 'acme/no-ai-test', ai: true, maxFiles: 1 }, { env: { OPENAI_API_KEY: 'server-test-placeholder', GENIUS_MODEL: 'test-model' }, fetchImpl: mock.fetchImpl }); assert.equal(result.ai, null); assert.ok(result.warnings.some(item => item.includes('no authorized key'))); assert.ok(mock.requests.every(item => item.url.startsWith('https://api.github.com/'))); }); // Require explicit instance authorization before spending a hosted key.
