// Project: Git Architecture Diagram | Hosting-runner startup regression test (Hostinger 503).
import test from 'node:test'; import assert from 'node:assert/strict'; // Use Node's built-in integration test facilities.
import { spawn } from 'node:child_process'; import { mkdtemp, writeFile, rm } from 'node:fs/promises'; import os from 'node:os'; import path from 'node:path'; import { fileURLToPath } from 'node:url'; // Run the entry file in separate processes, like a hosting panel does.
const ENTRY = fileURLToPath(new URL('../server.mjs', import.meta.url)); // The file configured as the hosting "Entry file".
// LiteSpeed lsnode.js and Passenger replace listen() with their own socket, then load the entry file from their own script, so process.argv[1] is the runner.
const RUNNER = `const http = require('node:http'); const real = http.Server.prototype.listen;
http.Server.prototype.listen = function (...args) { const done = args.find(arg => typeof arg === 'function'); return real.call(this, 0, '127.0.0.1', () => { console.log('RUNNER_PORT=' + this.address().port); if (done) done(); }); };
const entry = process.env.RUNNER_ENTRY; (process.env.RUNNER_MODE === 'import' ? import(require('node:url').pathToFileURL(entry).href) : Promise.resolve(require(entry))).catch(error => { console.error(error); process.exit(1); });`; // import() takes a file:// URL, so a Windows path such as D:\\app\\server.mjs is converted first; require() takes the path as is.
function launch(args, env) { const child = spawn(process.execPath, args, { env: { ...process.env, ...env }, stdio: ['ignore', 'pipe', 'pipe'] }); let output = ''; child.stdout.on('data', chunk => { output += chunk; }); child.stderr.on('data', chunk => { output += chunk; }); return { child, output: () => output }; } // Capture combined output for diagnostics.
async function waitFor(run, pattern, ms = 8000) { const end = Date.now() + ms; while (Date.now() < end) { const match = run.output().match(pattern); if (match) return match; if (run.child.exitCode !== null) break; await new Promise(resolve => setTimeout(resolve, 50)); } throw new Error(`The entry file never started listening (no ${pattern}). Output:\n${run.output()}`); } // Fail the way production fails: no listener means a 503 from the proxy.
async function assertServes(base) { const health = await fetch(base + '/api/health'); assert.equal(health.status, 200); assert.equal((await health.json()).ok, true); for (const route of ['/ProAmineOfficial/Driver-NanoKit-ESP32-of-T.U.M-Pro_Amine-IC', '/ProAmineOfficial/NanoKit-ESP32/tree/main/examples_on_platformio/ultrasonic_distance', '/ProAmineOfficial/NanoKit-ESP32/blob/main/README.md']) { const page = await fetch(base + route); assert.equal(page.status, 200); assert.ok((await page.text()).includes('Git Architecture Diagram')); } } // Health plus GitHub-style deep links must reach the workspace.
for (const mode of ['require', 'import']) test(`entry file serves requests when a hosting runner loads it with ${mode}()`, async t => { // Reproduce how Hostinger's Node runner starts the app.
  const dir = await mkdtemp(path.join(os.tmpdir(), 'gad-runner-')); const runner = path.join(dir, 'runner.cjs'); await writeFile(runner, RUNNER); t.after(() => rm(dir, { recursive: true, force: true })); // Keep the runner outside the project, like /usr/local/lsws/fcgi-bin/lsnode.js.
  const run = launch([runner], { RUNNER_ENTRY: ENTRY, RUNNER_MODE: mode, HOST: '0.0.0.0', PORT: '3000', PUBLIC_ORIGIN: 'https://gitarchitecturediagram.com', GIT_ARCHITECTURE_DIAGRAM_AUTOSTART: '' }); t.after(() => run.child.kill()); // Use the documented production variables.
  const [, port] = await waitFor(run, /RUNNER_PORT=(\d+)/); await assertServes(`http://127.0.0.1:${port}`); // The runner's socket must answer.
});
test('entry file still starts with node server.mjs and honors HOST and PORT', async t => { // Keep npm start, Docker, and local development behavior.
  const probe = (await import('node:net')).createServer(); await new Promise(resolve => probe.listen(0, '127.0.0.1', resolve)); const port = probe.address().port; await new Promise(resolve => probe.close(resolve)); // Reserve a free local port number.
  const run = launch([ENTRY], { HOST: '127.0.0.1', PORT: String(port), GIT_ARCHITECTURE_DIAGRAM_AUTOSTART: '' }); t.after(() => run.child.kill()); await waitFor(run, /is running at/); await assertServes(`http://127.0.0.1:${port}`); // Direct execution must answer on the configured port.
});
test('importing the server with autostart disabled does not open a listener', async () => { // Tests and tools can import createAppServer without side effects.
  const run = launch(['--input-type=module', '-e', `const m = await import(${JSON.stringify(new URL('../server.mjs', import.meta.url).href)}); console.log(typeof m.createAppServer);`], { GIT_ARCHITECTURE_DIAGRAM_AUTOSTART: '0', PORT: '0' }); // A lingering listener would keep this process alive.
  const code = await new Promise((resolve, reject) => { const timer = setTimeout(() => { run.child.kill(); reject(new Error('The import opened a listener and kept the process alive.')); }, 5000); run.child.on('exit', value => { clearTimeout(timer); resolve(value); }); }); assert.equal(code, 0); assert.match(run.output(), /function/); // The process exits on its own.
});
