// Project: Git Architecture Diagram | Real HTTP routing and browser-boundary integration checks.
import test from 'node:test'; import assert from 'node:assert/strict'; // Use Node's built-in integration test facilities.
import { createAppServer } from '../server.mjs'; // Start the actual application server on an ephemeral port.
test('HTTP serves deep links and local modules while protecting API and filesystem boundaries', async t => { // Exercise the public deployment contract without a live GitHub call.
  const server = createAppServer(); await new Promise(resolve => server.listen(0, '127.0.0.1', resolve)); t.after(() => new Promise(resolve => server.close(resolve))); const base = `http://127.0.0.1:${server.address().port}`; // Isolate the test from the developer's running server.
  for (const route of ['/', '/examples', '/acme/demo/blob/main/src/main.js', '/acme/project.js', '/acme/demo/tree/main/src/main.cpp']) { const response = await fetch(base + route); assert.equal(response.status, 200); assert.ok((await response.text()).includes('Git Architecture Diagram')); assert.ok(response.headers.get('content-security-policy').includes("object-src 'none'")); } // Verify domain-replacement URLs with dotted names and file scopes.
  const vendor = await fetch(base + '/vendor/mermaid/mermaid.esm.min.mjs'); assert.equal(vendor.status, 200); assert.ok(vendor.headers.get('content-type').includes('javascript')); await vendor.text(); // Confirm browser modules are available without a CDN.
  for (const route of ['/.env', '/server.mjs', '/vendor/mermaid/%2e%2e%2f%2e%2e%2fpackage.json']) { const response = await fetch(base + route); assert.equal(response.status, 404); await response.text(); } // Reject server files and encoded distribution-root traversal.
  const blocked = await fetch(base + '/api/analyze', { method: 'POST', headers: { Origin: 'https://evil.test', 'Content-Type': 'application/json' }, body: '{}' }); assert.equal(blocked.status, 403); await blocked.text(); // Reject hostile cross-origin requests before provider work.
  const invalidType = await fetch(base + '/api/analyze', { method: 'POST', body: '{}' }); assert.equal(invalidType.status, 415); await invalidType.text(); // Reject form-style submissions.
  const oversized = await fetch(base + '/api/analyze', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ repository: 'x'.repeat(21000) }) }); assert.equal(oversized.status, 413); await oversized.text(); // Bound incoming JSON before analysis.
  const invalidTarget = await fetch(base + '/api/analyze', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ repository: 'https://evil.test/a/b' }) }); assert.equal(invalidTarget.status, 200); const event = JSON.parse((await invalidTarget.text()).trim()); assert.equal(event.type, 'error'); assert.equal(event.status, 400); // Preserve actionable errors over the NDJSON streaming protocol.
}); // End real HTTP integration coverage.
