// Provider contracts and credential isolation are exercised without paid API requests.
import test from 'node:test'; import assert from 'node:assert/strict'; // Use the same built-in runner as the rest of the project.
import { explainWithAI } from '../src/ai.mjs'; import { providerOutput } from '../src/providers.mjs'; // Test the actual adapters and common reference validator.
import { runAnalysis } from '../src/service.mjs'; import { githubFixture } from './fixtures.mjs'; // Verify the service cannot forward one provider's server key to another.
const report = { repository: { fullName: 'acme/demo', sha: 'a'.repeat(40), entries: [{ path: 'main.js', type: 'blob' }] }, coverage: {}, dependencies: [], files: [{ path: 'main.js', content: 'export const value = 1;' }] }; // Keep an actual bounded citation target.
const answer = { overview: 'A source module.', components: [{ path: 'main.js', description: 'Exports a value.' }, { path: 'invented.js', description: 'Unverified.' }], relationships: [], recommendations: [], limitations: [] }; // Include an invalid path to prove all providers use the same validator.
const text = JSON.stringify(answer); const outputs = { openai: { status: 'completed', output: [{ content: [{ type: 'output_text', text }] }] }, anthropic: { stop_reason: 'end_turn', content: [{ type: 'text', text }] }, gemini: { candidates: [{ finishReason: 'STOP', content: { parts: [{ thought: true, text: 'Ignored' }, { text }] } }] }, kimi: { choices: [{ finish_reason: 'stop', message: { content: text, reasoning_content: 'Ignored' } }] } }; // Model final response envelopes from the official REST contracts.
const endpoints = { openai: ['api.openai.com', 'Authorization'], anthropic: ['api.anthropic.com', 'x-api-key'], gemini: ['generativelanguage.googleapis.com', 'x-goog-api-key'], kimi: ['api.moonshot.ai', 'Authorization'] }; // Allow only the selected provider's endpoint and authentication header.
test('every provider uses its native structured-output contract and validates source paths', async () => { // Cover the complete optional AI request and report path.
  for (const [provider, [host, keyHeader]] of Object.entries(endpoints)) { let calls = 0; const result = await explainWithAI(report, { provider, apiKey: 'provider-placeholder', model: provider === 'kimi' ? 'kimi-k3' : 'test-model', fetchImpl: async (url, options) => { calls++; assert.equal(new URL(url).hostname, host); assert.ok(!url.includes('provider-placeholder')); assert.equal(options.redirect, 'manual'); assert.ok(options.headers[keyHeader].includes('provider-placeholder')); const body = JSON.parse(options.body); const schema = provider === 'openai' ? body.text.format.schema : provider === 'anthropic' ? body.output_config.format.schema : provider === 'gemini' ? body.generationConfig.responseFormat.text.schema : body.response_format.json_schema.schema; assert.equal(schema.additionalProperties, false); if (provider === 'gemini') assert.equal(body.generationConfig.responseFormat.text.mimeType, 'APPLICATION_JSON'); if (provider === 'openai') assert.equal(body.store, false); if (provider === 'kimi') assert.equal(body.reasoning_effort, 'low'); return Response.json(outputs[provider]); } }); assert.equal(calls, 1); assert.equal(result.provider, provider); assert.equal(result.components.length, 1); assert.equal(result.discardedReferences, 1); assert.equal(result.overview, answer.overview); } // Use actual output normalization instead of echoing the request implementation.
}); // End provider contract coverage.
test('refusals, truncation, HTML, and redirects leave a clear optional-provider failure', async () => { // Prevent another raw invalid-JSON regression at the provider boundary.
  for (const [provider, output] of [['openai', { status: 'incomplete' }], ['anthropic', { stop_reason: 'max_tokens' }], ['gemini', { candidates: [{ finishReason: 'MAX_TOKENS' }] }], ['kimi', { choices: [{ finish_reason: 'length' }] }]]) assert.throws(() => providerOutput(provider, output), /incomplete/); // Reject partial answers before decoding their JSON.
  for (const response of [new Response('<!DOCTYPE html>Unavailable', { status: 200 }), new Response('', { status: 302, headers: { Location: 'https://untrusted.example/' } })]) { let calls = 0; await assert.rejects(explainWithAI(report, { provider: 'anthropic', apiKey: 'placeholder', model: 'test-model', fetchImpl: async () => { calls++; return response; } }), /unreadable|HTTP 302/); assert.equal(calls, 1); } // Never follow a redirect carrying caller credentials.
}); // End incomplete-response coverage.
test('changing the selected provider never reuses another provider server credential', async () => { const fixture = githubFixture({ name: 'provider-isolation' }); const result = await runAnalysis({ repository: 'acme/provider-isolation', maxFiles: 1, ai: true, provider: 'anthropic', model: 'test-model' }, { env: { OPENAI_API_KEY: 'openai-server-placeholder', GENIUS_PROVIDER: 'openai', GENIUS_MODEL: 'test-model' }, allowEnvAI: true, fetchImpl: fixture.fetchImpl }); assert.equal(result.ai, null); assert.ok(result.warnings.some(item => item.includes('no authorized key'))); assert.ok(fixture.requests.every(item => new URL(item.url).hostname === 'api.github.com')); }); // Guard server environment fallback independently of the UI's key clearing.
