// Repository questions: source validation, explicit paid consent, and provider failure contracts.
import test from 'node:test'; import assert from 'node:assert/strict'; // Exercise real orchestration with deterministic upstream contracts.
import { runQuestion, answerQuestionWithAI, questionContext, validateQuestionAnswer } from '../src/question.mjs'; // Exercise the shipped question service.
import { githubFixture, commitSHA, files, entries } from './fixtures.mjs'; // Use the existing integrity-checked GitHub fixture.
const result = { repository: { fullName: 'acme/demo', sha: commitSHA, scope: '', entries, htmlUrl: 'https://github.com/acme/demo' }, files }; // Model trusted in-memory analysis evidence.
const raw = { findings: [{ text: 'The entry module imports its helper.', basis: 'source', citations: [{ path: 'src/main.js', line: 2, quote: 'import { helper } from "./helper.js";' }] }], limitations: ['Only sampled source was read.'], suggestedQuestions: ['What does the helper export?'] }; // Include an exact factual citation.
const envelope = value => Response.json({ status: 'completed', output: [{ content: [{ type: 'output_text', text: JSON.stringify(value) }] }] }); // Return a raw OpenAI response without spending model credits.
test('stateless questions pin source and make one provider call with isolated credentials', async () => { const mock = githubFixture(); let paid = 0; const answer = await runQuestion({ repository: 'acme/demo', commit: commitSHA, question: 'Where is helper imported?', evidencePaths: ['src/main.js'], ai: true, provider: 'openai', apiKey: 'ai-placeholder', githubToken: 'github-placeholder', model: 'test-model' }, { env: {}, fetchImpl: async (url, options) => { if (new URL(url).hostname === 'api.github.com') { assert.equal(options.headers.Authorization, 'Bearer github-placeholder'); return mock.fetchImpl(url, options); } paid++; assert.equal(url, 'https://api.openai.com/v1/responses'); assert.equal(options.headers.Authorization, 'Bearer ai-placeholder'); const body = JSON.parse(options.body); assert.equal(body.max_output_tokens, 3000); assert.equal(body.store, false); assert.equal(JSON.parse(body.input).commit, commitSHA); return envelope(raw); } }); assert.equal(paid, 1); assert.equal(mock.requests.length, 4); assert.equal(answer.findings[0].citations[0].url, `https://github.com/acme/demo/blob/${commitSHA}/src/main.js#L2`); assert.equal(JSON.stringify(answer).includes('placeholder'), false); }); // Verify one paid call and four bounded GitHub reads end to end.
test('missing consent and provider isolation reject before outbound work', async () => { let calls = 0; const fetchImpl = async () => { calls++; throw new Error('Unexpected request'); }; await assert.rejects(runQuestion({ repository: 'acme/demo', question: 'Why?' }, { fetchImpl }), /Confirm Ask Genius/); await assert.rejects(runQuestion({ repository: 'acme/demo', commit: commitSHA, question: 'Why?', ai: true, provider: 'anthropic', model: 'test-model' }, { allowEnvAI: true, env: { GENIUS_PROVIDER: 'openai', OPENAI_API_KEY: 'server-placeholder' }, fetchImpl }), /API key/); assert.equal(calls, 0); }); // Prove a configured provider key cannot enable a different provider or implicit spending.
test('private source cannot be read through only the server GitHub token', async () => { const mock = githubFixture({ privateRepo: true }); await assert.rejects(runQuestion({ repository: 'acme/demo', commit: commitSHA, question: 'What is this?', ai: true, apiKey: 'ai-placeholder', model: 'test-model' }, { env: { GITHUB_TOKEN: 'server-placeholder' }, fetchImpl: mock.fetchImpl }), /own request-specific/); assert.equal(mock.requests.length, 1); }); // Preserve the established private-repository authorization boundary.
test('unsupported findings are removed as a whole', () => { const context = questionContext(result, 'helper'); const fabricated = structuredClone(raw); fabricated.findings.push({ text: 'A fake claim.', basis: 'source', citations: [{ path: 'fake.js', line: 1, quote: 'fake' }] }); fabricated.findings.push({ text: 'A wrong quotation.', basis: 'inference', citations: [{ path: 'src/main.js', line: 2, quote: 'runAdmin();' }] }); const answer = validateQuestionAnswer(fabricated, result, context); assert.equal(answer.findings.length, 1); assert.equal(answer.discardedFindings, 2); assert.match(answer.limitations.at(-1), /2 finding/); }); // Never leave generated prose with an invalid citation silently removed.
test('question excerpts and citation locations remain bounded', () => { const big = { ...result, files: [{ path: 'src/main.js', content: Array.from({ length: 1000 }, (_, index) => `line ${index} ` + 'a'.repeat(1000)).join('\n') }] }; const context = questionContext(big, 'line'); assert.ok(context.sourceCharacters <= 24000); assert.ok(context.payload.excerpts[0].lines.length < 1000); assert.equal(context.citedLines.get('src/main.js\0' + context.payload.excerpts[0].lines[0].line), context.payload.excerpts[0].lines[0].text.trim()); }); // Count supplied lines rather than claiming the whole file was included.
test('HTML, malformed envelopes, redirects, and invalid JSON get bounded errors', async () => { for (const [response, match] of [[new Response('<!DOCTYPE html>Unavailable'), /page instead/], [Response.json({ output: {} }), /invalid answer envelope/], [new Response('', { status: 302, headers: { Location: 'https://evil.example' } }), /HTTP 302/], [Response.json({ output: [{ content: [{ type: 'output_text', text: '{bad' }] }] }), /invalid answer JSON/]]) await assert.rejects(answerQuestionWithAI(result, { question: 'Where is helper?', apiKey: 'placeholder', model: 'test-model', fetchImpl: async (_, options) => { assert.equal(options.redirect, 'manual'); return response; } }), match); }); // Protect the new endpoint from the existing invalid-JSON failure class.
test('aborting a paid request remains cancellation, never a successful answer', async () => { const controller = new AbortController(); await assert.rejects(answerQuestionWithAI(result, { question: 'Where is helper?', apiKey: 'placeholder', model: 'test-model', signal: controller.signal, fetchImpl: async () => { controller.abort(); throw new Error('aborted'); } }), error => error.status === 499); }); // Propagate cancellation across provider error translation.
