// Navigation regressions cover real user state transitions without network calls or provider costs.
import test from 'node:test'; import assert from 'node:assert/strict'; // Use the project's existing test framework.
import { parseGitHubInput, parseWorkspaceRoute, parseLineAnchor, lineAnchor, analysisInputForRoute, resolveRepositoryState, buildWorkspaceURL } from '../public/route-state.js'; // Exercise the proposed pure route-state contract.
const sha = 'a'.repeat(40); const origin = 'https://diagram.example'; // Keep all fixtures detached from live accounts.
const repository = { fullName: 'acme/demo', sha, branch: 'feature/ui', scope: 'src', entries: [{ path: 'src', type: 'tree' }, { path: 'src/main.js', type: 'blob' }] }; // Represent identity and paths verified by GitHub ingestion.
test('replacement routes retain slash-containing and encoded refs for backend resolution', () => { // Do not guess which slash belongs to the branch.
  for (const tail of ['feature/ui/src', 'feature%2Fui/src']) { const state = parseWorkspaceRoute(`${origin}/acme/demo/tree/${tail}`); assert.equal(state.repository, `https://github.com/acme/demo/tree/${tail}`); assert.equal(analysisInputForRoute(state).ref, ''); const resolved = resolveRepositoryState(state, repository); assert.equal(resolved.scope, 'src'); assert.equal(resolved.selectedRef, 'feature/ui'); assert.equal(resolved.repository, 'https://github.com/acme/demo'); } // Preserve initial route semantics and remove ambiguity after resolution.
}); // End slash-ref coverage.
test('an unresolved blob route can enter history without losing its path or anchor', () => { // A visitor may navigate while initial analysis is still pending.
  const state = parseGitHubInput('https://github.com/acme/demo/blob/feature%2Fui/src/main.js?plain=1#L3-L7'); const shared = new URL(buildWorkspaceURL(state, origin)); assert.equal(shared.pathname, '/acme/demo/blob/feature%2Fui/src/main.js'); assert.equal(shared.hash, '#L3-L7'); const restored = parseWorkspaceRoute(shared.href); assert.equal(restored.repository, state.repository); assert.equal(restored.line, 3); assert.equal(restored.endLine, 7); // Retain the original branch/path boundary until the backend resolves it.
}); // End pending-route round trip.
test('snapshot shares retain selected branch and refresh its new commit instead of the pinned one', () => { // Protect the refresh-after-reload journey.
  const initial = parseGitHubInput('https://github.com/acme/demo/tree/feature/ui/src'); const resolved = resolveRepositoryState(initial, repository); const reloaded = parseWorkspaceRoute(buildWorkspaceURL(resolved, origin)); assert.equal(analysisInputForRoute(reloaded).ref, sha); assert.equal(analysisInputForRoute(reloaded, { refresh: true }).ref, 'feature/ui'); assert.equal(analysisInputForRoute(reloaded, { refresh: true }).scope, 'src'); // Share immutable source while preserving explicit update behavior.
}); // End selected-reference round trip.
test('blob links preserve Unicode paths, query preference, and inclusive line ranges', () => { // Protect direct code-line deep links.
  const file = 'src/sensor α #1.js'; const encoded = file.split('/').map(encodeURIComponent).join('/'); const initial = parseGitHubInput(`https://github.com/acme/demo/blob/main/${encoded}?plain=1#L12-L19`); assert.deepEqual({ line: initial.line, endLine: initial.endLine }, { line: 12, endLine: 19 }); const resolved = resolveRepositoryState(initial, { ...repository, branch: 'main', scope: file, entries: [{ path: file, type: 'blob' }] }); const shared = buildWorkspaceURL(resolved, origin); const reloaded = parseWorkspaceRoute(shared); assert.equal(reloaded.selectedPath, file); assert.equal(reloaded.scope, file); assert.equal(reloaded.plain, true); assert.equal(new URL(shared).hash, '#L12-L19'); // Keep encoded path characters separate from the anchor delimiter.
}); // End source-line round trip.
test('history state preserves view and verified selection without serializing credentials', () => { // History and share URLs should carry the same safe navigation state.
  const initial = parseWorkspaceRoute(`${origin}/acme/demo?ref=${sha}&selectedRef=feature%2Fui&scope=src&view=mindmap&path=src%2Fmain.js#L2`); const state = resolveRepositoryState(initial, repository); const restored = parseWorkspaceRoute(buildWorkspaceURL({ ...state, apiKey: 'secret-placeholder', githubToken: 'private-placeholder', provider: 'openai', ai: true }, origin)); assert.equal(restored.view, 'mindmap'); assert.equal(restored.selectedPath, 'src/main.js'); assert.equal(restored.line, 2); assert.equal(restored.selectedRef, 'feature/ui'); const link = buildWorkspaceURL(state, origin); assert.ok(!link.includes('placeholder')); assert.ok(!link.includes('apiKey')); assert.ok(!link.includes('provider')); // Leave credentials and paid generation outside route state.
}); // End safe history serialization.
test('home/examples never become repository analyses and hosting budgets are enforced', () => { // Handle ordinary site navigation separately from repository routes.
  assert.deepEqual(parseWorkspaceRoute(`${origin}/`), { kind: 'home' }); assert.deepEqual(parseWorkspaceRoute(`${origin}/examples/`), { kind: 'examples' }); assert.throws(() => analysisInputForRoute({ kind: 'examples' })); assert.equal(parseWorkspaceRoute(`${origin}/acme/demo?files=120`, { maxFiles: 40 }).files, 40); for (const value of ['0', '-1', 'NaN', '1.5', 'Infinity']) assert.throws(() => parseWorkspaceRoute(`${origin}/acme/demo?files=${value}`)); // Reject malformed inputs before analysis admission.
}); // End route kind and budget coverage.
test('unknown selections and malformed anchors cannot manufacture source evidence', () => { // Bind a line only after its file exists in the returned inventory.
  for (const hash of ['#L0', '#L9-L2', '#L9007199254740992', '#readme', '#L1%0A']) assert.equal(parseLineAnchor(hash), null); assert.equal(lineAnchor({ line: 2, endLine: 4 }), '#L2-L4'); assert.equal(lineAnchor({ line: 2, endLine: 1 }), ''); const initial = parseWorkspaceRoute(`${origin}/acme/demo?path=missing.js#L5`); const resolved = resolveRepositoryState(initial, repository); assert.equal(resolved.selectedPath, ''); assert.equal(resolved.line, null); const folder = resolveRepositoryState(parseWorkspaceRoute(`${origin}/acme/demo?path=src&type=tree#L5`), repository); assert.equal(folder.selectedType, 'tree'); assert.equal(folder.line, null); // Clear impossible line selections rather than pointing elsewhere.
}); // End untrusted location validation.
test('legacy pinned links stay pinned when no original branch is known', () => { // Avoid guessing a moving branch from a SHA-only shared link.
  const state = parseWorkspaceRoute(`${origin}/acme/demo?ref=${sha}`); assert.equal(state.snapshotRef, sha); assert.equal(state.selectedRef, sha); assert.equal(analysisInputForRoute(state, { refresh: true }).ref, sha); // The UI can label this action Refresh snapshot and offer an explicit branch choice.
}); // End backward-compatible snapshot handling.
test('pasted URLs never select arbitrary upstream hosts or unsupported destinations', () => { // Preserve the current fixed-GitHub transport boundary.
  for (const input of ['https://evil.example/acme/demo', 'http://github.com/acme/demo', 'https://user:pass@github.com/acme/demo', 'https://github.com:123/acme/demo', 'acme/demo/issues/1', 'https://github.com/acme/demo/tree', 'https://github.com/acme/demo/tree/main/%ZZ', 'https://github.com/acme/demo/tree/main/src%2F..%2Fprivate']) assert.throws(() => parseGitHubInput(input)); assert.equal(parseGitHubInput('acme/demo.git').fullName, 'acme/demo'); // Accept ordinary clone input while excluding unrelated routes.
}); // End input destination coverage.

test('a parent proven by scoped descendants survives sharing without a fabricated line', () => { const state = parseWorkspaceRoute(`${origin}/acme/demo?scope=src%2Fmain.js&path=src&type=tree#L3`); const resolved = resolveRepositoryState(state, { ...repository, scope: 'src/main.js', entries: [{ path: 'src/main.js', type: 'blob' }] }); assert.equal(resolved.selectedPath, 'src'); assert.equal(resolved.selectedType, 'tree'); assert.equal(resolved.line, null); assert.equal(parseWorkspaceRoute(buildWorkspaceURL(resolved, origin)).selectedPath, 'src'); }); // Keep synthetic tree parents consistent with the source inspector.
