// Project: Git Architecture Diagram | Actual Workers runtime regression test.
import test from 'node:test'; import assert from 'node:assert/strict'; // Verify the production protocol in workerd instead of relying only on Node's Fetch API.
import { build } from 'esbuild'; // Compile the same Worker entrypoint used for publication without retaining generated files.
import { Miniflare } from 'miniflare'; // Run the compiled handler in the stable Cloudflare Workers testing runtime.
import { githubFixture, commitSHA } from './fixtures.mjs'; // Supply deterministic upstream evidence without using GitHub quota or model credits.
import { readAnalysisResponse, readQuestionResponse } from '../public/analysis-stream.js'; // Consume the native runtime's response with the actual browser parser.
test('workerd performs GitHub ingestion and optional AI without unsupported fetch options', async () => { // Exercise both external providers through native Workers fetch.
  const fixture = githubFixture({ name: 'native-runtime' }); const outbound = []; const { outputFiles } = await build({ entryPoints: ['worker.mjs'], bundle: true, write: false, format: 'esm', platform: 'neutral', external: ['node:*'] }); // Bundle the real implementation and preserve the runtime's Node compatibility imports.
  const runtime = new Miniflare({ modules: true, script: outputFiles[0].text, compatibilityDate: '2026-07-30', compatibilityFlags: ['nodejs_compat'], cf: false, outboundService: async request => { const url = new URL(request.url); outbound.push({ host: url.hostname, authorization: request.headers.get('Authorization') }); if (url.hostname === 'api.github.com') return fixture.fetchImpl(request.url, { headers: Object.fromEntries(request.headers) }); assert.equal(url.href, 'https://api.openai.com/v1/responses'); const body = await request.json(); assert.equal(body.store, false); return Response.json({ model: 'test-model', output: [{ content: [{ type: 'output_text', text: JSON.stringify(body.text.format.schema.properties.findings ? { findings: [{ text: 'The entry imports the helper.', basis: 'source', citations: [{ path: 'src/main.js', line: 2, quote: 'import { helper } from \"./helper.js\";' }] }], limitations: [], suggestedQuestions: [] } : { overview: 'Runtime fixture', components: [], relationships: [], recommendations: [], limitations: [] }) }] }] }); } }); // Replace only network destinations; request construction, streams, crypto, and fetch options stay native.
  try { const response = await runtime.dispatchFetch('http://runtime.test/api/analyze', { method: 'POST', headers: { 'Content-Type': 'application/json', Origin: 'http://runtime.test' }, body: JSON.stringify({ repository: 'acme/native-runtime', maxFiles: 2, ai: true, apiKey: 'ai-test-placeholder', githubToken: 'github-test-placeholder', model: 'test-model' }) }); const report = await readAnalysisResponse(response); assert.equal(report.repository.sha, commitSHA); assert.equal(report.coverage.readFiles, 2); assert.equal(report.ai.overview, 'Runtime fixture'); assert.match(report.diagrams.architecture, /^flowchart/); assert.match(report.diagrams.mindmap, /^mindmap/); assert.equal(outbound.filter(item => item.host === 'api.github.com').length, 5); assert.ok(outbound.filter(item => item.host === 'api.github.com').every(item => item.authorization === 'Bearer github-test-placeholder')); assert.equal(outbound.find(item => item.host === 'api.openai.com').authorization, 'Bearer ai-test-placeholder'); const source = await runtime.dispatchFetch('http://runtime.test/api/source', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ repository: 'acme/native-runtime', commit: commitSHA, path: 'src/main.js' }) }); assert.equal(source.status, 200); assert.match((await source.json()).file.content, /helper/); const answer = await readQuestionResponse(await runtime.dispatchFetch('http://runtime.test/api/ask', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ repository: 'acme/native-runtime', commit: commitSHA, evidencePaths: ['src/main.js'], question: 'Which helper is imported?', ai: true, apiKey: 'question-test-placeholder', model: 'test-model' }) })); assert.equal(answer.findings.length, 1); assert.equal(answer.findings[0].citations[0].line, 2); assert.equal(outbound.filter(item => item.host === 'api.openai.com').length, 2); } finally { await runtime.dispose(); } // Require a finished report with both diagram sources and keep provider credentials isolated.
}); // End native runtime verification.
