// Workspace interaction contracts use the real app and a stubbed diagram renderer; this is not browser layout QA.
import test from 'node:test'; import assert from 'node:assert/strict'; import { readFile } from 'node:fs/promises'; import { fileURLToPath } from 'node:url'; // Load the actual application assets and isolated assertions.
import { JSDOM } from 'jsdom'; import { build } from 'esbuild'; import { unzipSync, strFromU8 } from 'fflate'; // Exercise DOM interactions, bundled modules, and real ZIP exports.
import { runAnalysis } from '../src/service.mjs'; import { githubFixture, files, commitSHA } from './fixtures.mjs'; // Use real structural reports backed by deterministic GitHub responses.
const root = fileURLToPath(new URL('../', import.meta.url)); const html = await readFile(root + 'public/index.html', 'utf8'); // Resolve assets independently of the test working directory.
const aliases = { '/vendor/dompurify/purify.es.mjs': 'node_modules/dompurify/dist/purify.es.mjs', '/vendor/marked/marked.esm.js': 'node_modules/marked/lib/marked.esm.js', '/vendor/fflate/browser.js': 'node_modules/fflate/esm/browser.js', '/shared/evidence.mjs': 'src/evidence.mjs' }; // Preserve the production module boundary except for diagram geometry.
const bundle = await build({ entryPoints: [root + 'public/app.js'], bundle: true, write: false, format: 'iife', platform: 'browser', plugins: [{ name: 'workspace-contract', setup(builder) { builder.onResolve({ filter: /^\/vendor\/mermaid\// }, () => ({ path: 'mermaid', namespace: 'diagram-stub' })); builder.onLoad({ filter: /.*/, namespace: 'diagram-stub' }, () => ({ contents: `export default {initialize(){},async render(id,source){const nodes=[...source.matchAll(/^\\s*((?:n|o|agn)\\d+|b\\d+f\\d+)(?:\\[|\\()/gm)].map(m=>'<g class="node '+(m[1].startsWith('b')?'gad-'+m[1]:'')+'" id="flowchart-'+m[1]+'-0"><text>Source</text></g>').join('');return {svg:'<svg viewBox="0 0 800 500">'+nodes+'</svg>'};}};` })); builder.onResolve({ filter: /^\/(?:vendor|shared)\// }, args => ({ path: root + aliases[args.path] })); } }] }); // Substitute rendering only, retaining all route, selection, security, and export code.
async function report(name = 'workspace', scope = '') { const fixture = githubFixture({ name }); return runAnalysis({ repository: `acme/${name}`, maxFiles: 6, scope }, { env: {}, fetchImpl: fixture.fetchImpl, cachePublic: false, retainSession: false }); } // Build each independent fixture through the shipped analyzer.
async function waitFor(predicate) { for (let count = 0; count < 200; count++) { if (predicate()) return; await new Promise(resolve => setTimeout(resolve, 5)); } assert.fail('The expected workspace state did not appear.'); } // Bound asynchronous UI assertions without long arbitrary sleeps.
function setup(route, transport) { // Provide DOM capabilities needed by the app without pretending to implement browser layout.
  const dom = new JSDOM(html, { url: 'https://diagram.example' + route, runScripts: 'outside-only' }); const w = dom.window; const calls = []; const downloads = []; const urls = new Map(); const opened = []; // Keep external actions observable within the isolated test.
  w.matchMedia = () => ({ matches: true }); w.Element.prototype.scrollIntoView = () => {}; w.Element.prototype.hasPointerCapture = () => false; w.Element.prototype.setPointerCapture = () => {}; w.Element.prototype.releasePointerCapture = () => {}; w.AbortController = AbortController; w.TextDecoder = TextDecoder; w.Blob = Blob; w.open = url => opened.push(url); // Stub unavailable browser layout/input capabilities explicitly.
  w.URL.createObjectURL = blob => { const url = `blob:test-${urls.size}`; urls.set(url, blob); return url; }; w.URL.revokeObjectURL = () => {}; w.HTMLAnchorElement.prototype.click = function () { if (this.download) downloads.push({ name: this.download, blob: urls.get(this.href) }); }; // Capture actual exported bytes without initiating a real browser download.
  w.fetch = async (url, options = {}) => { if (url === '/api/health') return Response.json({ limits: { maxFiles: 40 } }); const body = options.body ? JSON.parse(options.body) : {}; calls.push({ url, body, signal: options.signal }); return transport(url, body, options); }; w.eval(bundle.outputFiles[0].text); return { dom, w, calls, downloads, opened, $: selector => w.document.querySelector(selector) }; // Start the real UI with controlled network responses.
} // End DOM setup.
const stream = value => new Response(JSON.stringify({ type: 'result', result: value }) + '\n', { headers: { 'Content-Type': 'application/x-ndjson' } }); // Replay complete reports through the production stream reader.
test('blob routes restore ranges, source selection, view edits, themes, and real documentation exports', async t => { // Protect the user's source-linked diagram workflow.
  const result = await report('workspace', 'src/main.js'); const source = result.files.find(item => item.path === 'src/main.js'); source.content = Array.from({ length: 400 }, (_, index) => `source line ${index + 1}`).join('\n'); const ui = setup('/acme/workspace/blob/feature/ui/src/main.js#L320-L322', async () => stream(result)); t.after(() => ui.dom.window.close()); const { $, w } = ui; await waitFor(() => $('#file-code').textContent.includes('source line 320')); // A shared anchor must not be lost or hidden behind the first 240 lines.
  assert.match(w.location.hash, /L320-L322/); assert.match($('#source-link').href, /#L320-L322$/); assert.equal(w.document.querySelectorAll('.source-line[data-highlight=true]').length, 3); assert.equal(ui.calls[0].body.ai, false); // Verify exact range restoration and free automatic analysis.
  $('button[aria-label=\"Inspect folder src\"]').click(); assert.equal(w.document.querySelectorAll('#tree summary.selected').length, 1); $('.tree-file[data-path=\"src/main.js\"]').click(); assert.equal(w.document.querySelectorAll('#tree summary.selected').length, 0); $('#architecture-mode').value = 'source'; $('#architecture-mode').dispatchEvent(new w.Event('change')); await waitFor(() => w.document.querySelector('#diagram-content [data-source-node]')); const mapped = $('#diagram-content [data-source-node]'); mapped.dispatchEvent(new w.KeyboardEvent('keydown', { key: 'Enter', bubbles: true })); assert.equal($('#file-name').textContent, 'src/main.js'); assert.equal($('#diagram-content [data-selected-source=true]') !== null, true); // Synchronize keyboard graph selection with the real source inspector.
  $('#mermaid-source').value = 'flowchart TD\nn0[Edited]'; $('#render-source').click(); await waitFor(() => $('#diagram-content svg')); assert.equal($('#diagram-content [data-source-node]'), null); $('#theme').click(); await waitFor(() => $('#diagram-content svg')); assert.equal($('#diagram-content [data-source-node]'), null); // Edited diagrams cannot inherit stale path mappings after a theme change.
  $('#toggle-tree').click(); assert.equal($('#tree-panel').hidden, true); assert.equal($('#toggle-tree').getAttribute('aria-expanded'), 'false'); $('#toggle-tree').click(); // Preserve accessible sidebar state.
  $('#export-format').value = 'mmd'; $('#export-format').dispatchEvent(new w.Event('change')); $('#export-guide').click(); await waitFor(() => ui.downloads.length === 2); assert.equal(await ui.downloads[0].blob.text(), 'flowchart TD\nn0[Edited]'); const entries = unzipSync(new Uint8Array(await ui.downloads[1].blob.arrayBuffer())); assert.ok(entries['.genius/component-overview.mmd']); assert.ok(strFromU8(entries['.genius/evidence.json']).includes(commitSHA)); assert.ok(!strFromU8(entries['.genius/evidence.json']).includes('apiKey')); // Verify actual edited Mermaid and ZIP contents, not merely enabled buttons.
}); // End source and export contract.
test('Back restores prior repository and Refresh uses its selected branch without paid replay', async t => { const first = await report('first'); const second = await report('second'); const ui = setup('/acme/first', async (_, input) => stream(input.repository.includes('second') ? second : first)); t.after(() => ui.dom.window.close()); const { $, w } = ui; await waitFor(() => $('#repo-title').textContent === 'acme/first'); $('#repository').value = 'acme/second'; $('#ref').value = 'feature/ui'; $('#use-ai').checked = true; $('#analyze-form').dispatchEvent(new w.Event('submit', { bubbles: true, cancelable: true })); await waitFor(() => $('#repo-title').textContent === 'acme/second'); assert.equal(ui.calls.at(-1).body.ai, true); w.history.back(); await waitFor(() => $('#repo-title').textContent === 'acme/first' && !$('#workspace').hidden); assert.equal(ui.calls.at(-1).body.ai, false); $('#refresh').click(); await waitFor(() => ui.calls.at(-1).body.refresh === true); assert.equal(ui.calls.at(-1).body.ref, 'main'); assert.equal(ui.calls.at(-1).body.ai, false); }); // Prevent pinned snapshots and checked AI settings from breaking history or causing automatic spend.
test('on-demand source browsing and explicitly paid questions use separate endpoints', async t => { const result = await report(); result.files = result.files.filter(item => item.path !== 'src/helper.js'); const ui = setup('/acme/workspace', async (url, input) => { if (url === '/api/source') return Response.json({ file: files.find(item => item.path === input.path), commit: commitSHA }); if (url === '/api/ask') return new Response(JSON.stringify({ type: 'answer', answer: { mode: 'ai-answer', providerName: 'Mock provider', model: 'test-model', findings: [{ text: 'The helper is imported.', basis: 'source', citations: [{ path: 'src/main.js', line: 2, quote: 'import' }] }], limitations: [], suggestedQuestions: ['Where is it called?'], citationValidation: 'Mock integration response.' } }) + '\n', { headers: { 'Content-Type': 'application/x-ndjson' } }); return stream(result); }); t.after(() => ui.dom.window.close()); const { $, w } = ui; await waitFor(() => $('#repo-title').textContent); $('#tree-filter').value = 'unread'; $('#tree-filter').dispatchEvent(new w.Event('change')); $('.tree-file[data-path="src/helper.js"]').click(); assert.equal($('#load-source').hidden, false); $('#load-source').click(); await waitFor(() => $('#file-code').textContent.includes('ready')); assert.equal(ui.calls.at(-1).url, '/api/source'); assert.match($('#file-info').textContent, /coverage unchanged/); // Read source without claiming it was part of the original analysis.
  $('#question').value = 'helper'; $('#ask-form').dispatchEvent(new w.Event('submit', { cancelable: true })); assert.equal(ui.calls.some(item => item.url === '/api/ask'), false); $('#question-mode').value = 'ai'; $('#question-mode').dispatchEvent(new w.Event('change')); assert.match($('#question-disclosure').textContent, /One paid request/); $('#api-key').value = 'test-placeholder'; $('#ask-form').dispatchEvent(new w.Event('submit', { cancelable: true })); await waitFor(() => $('#search-results').textContent.includes('The helper is imported.')); const paid = ui.calls.filter(item => item.url === '/api/ask'); assert.equal(paid.length, 1); assert.equal(paid[0].body.ai, true); assert.equal(paid[0].body.commit, commitSHA); assert.ok(paid[0].body.evidencePaths.length <= 8); assert.equal(w.location.href.includes('test-placeholder'), false); // Require the paid mode and deliberate submit while retaining immutable evidence.
  const suggestion = [...w.document.querySelectorAll('.answer-citation')].at(-1); suggestion.click(); assert.equal($('#question').value, 'Where is it called?'); assert.equal(ui.calls.filter(item => item.url === '/api/ask').length, 1); // Suggested questions fill the input without purchasing another answer.
}); // End source and question UI contract.
test('a stale analysis cannot overwrite a newer route after cancellation', async t => { const slow = await report('slow'); const fast = await report('fast'); let release; const deferred = new Promise(resolve => { release = resolve; }); const ui = setup('/acme/slow', async (_, input) => input.repository.includes('slow') ? deferred : stream(fast)); t.after(() => ui.dom.window.close()); await waitFor(() => ui.calls.length === 1); ui.w.history.pushState({}, '', '/acme/fast'); ui.w.dispatchEvent(new ui.w.PopStateEvent('popstate')); await waitFor(() => ui.$('#repo-title').textContent === 'acme/fast'); release(stream(slow)); await new Promise(resolve => setTimeout(resolve, 20)); assert.equal(ui.$('#repo-title').textContent, 'acme/fast'); assert.equal(ui.calls[0].signal.aborted, true); }); // Reproduce a late upstream response rather than only testing a helper in isolation.

test('invalid read budgets surface an error without mutating history or starting another request', async t => { const result = await report(); const ui = setup('/acme/workspace', async () => stream(result)); t.after(() => ui.dom.window.close()); await waitFor(() => ui.$('#repo-title').textContent); const before = ui.w.location.href; ui.$('#max-files').value = ''; ui.$('#analyze-form').dispatchEvent(new ui.w.Event('submit', { cancelable: true })); await waitFor(() => !ui.$('#status').hidden); assert.match(ui.$('#status-text').textContent, /positive whole number/); assert.equal(ui.calls.length, 1); assert.equal(ui.w.location.href, before); assert.equal(ui.$('#analyze').disabled, false); }); // Keep malformed form input inside the visible error boundary.
