// Project: Git Architecture Diagram | Hosted routing, source analysis, and publication contract tests.
import test from 'node:test'; import assert from 'node:assert/strict'; // Test the real Fetch API Worker without provider credentials.
import { createWorker } from '../worker.mjs'; // Exercise the handler deployed to the public website.
import { runAnalysis, getSession } from '../src/service.mjs'; // Validate that hosting still uses the original source analysis engine.
import { analyzeSnapshot, fileRole, ROLE_PALETTE } from '../src/genius.mjs'; // Check the requested semantic-color contract without changing authored diagrams.
import { githubFixture, files, entries, commitSHA } from './fixtures.mjs'; // Reuse verified deterministic source fixtures.
const assets = { fetch: async request => new URL(request.url).pathname === '/index.html' ? new Response('<!doctype html><title>Git Architecture Diagram</title>', { headers: { 'Content-Type': 'text/html' } }) : new Response('Not found', { status: 404 }) }; // Emulate the platform's asset binding rather than a filesystem server.
const request = (body, extra = {}) => new Request('https://diagram.example/api/analyze', { method: 'POST', headers: { 'Content-Type': 'application/json', Origin: 'https://diagram.example', ...extra }, body: typeof body === 'string' ? body : JSON.stringify(body) }); // Build realistic browser JSON requests.
test('hosted root, dotted repository, and nested GitHub folder URLs serve the workspace', async () => { const worker = createWorker(); for (const route of ['/', '/acme/project.js', '/ProAmineOfficial/NanoKit-ESP32/tree/main/examples_on_platformio/ultrasonic_distance/docs']) { const response = await worker.fetch(new Request(`https://diagram.example${route}`), { ASSETS: assets }); assert.equal(response.status, 200); assert.ok((await response.text()).includes('Git Architecture Diagram')); assert.ok(response.headers.get('Content-Security-Policy').includes("object-src 'none'")); } const missing = await worker.fetch(new Request('https://diagram.example/.env'), { ASSETS: assets }); assert.equal(missing.status, 404); }); // Cover the exact failed URL shape from the user's screenshot.
test('hosted analysis streams verified source results without retaining a server session', async () => { const fixture = githubFixture({ name: 'hosted-test' }); const worker = createWorker({ analyze: (input, options) => runAnalysis(input, { ...options, fetchImpl: fixture.fetchImpl }) }); const response = await worker.fetch(request({ repository: 'acme/hosted-test', maxFiles: 12 }), {}); assert.equal(response.headers.get('Content-Type'), 'application/x-ndjson'); const events = (await response.text()).trim().split('\n').map(JSON.parse); assert.ok(events.some(event => event.type === 'progress')); const result = events.find(event => event.type === 'result').result; assert.equal(result.repository.sha, commitSHA); assert.equal(result.coverage.readFiles, files.length); assert.equal(result.dependencies.length, 1); assert.ok(result.diagrams.legend.length > 1); assert.equal(result.cacheHit, false); assert.throws(() => getSession(result.id), /expired/); }); // Ensure hosted reports are real, source-grounded, and independent of isolate-local sessions.
test('hosted API enforces origins, access, JSON sizes, and the disclosed file budget', async () => { let calls = 0; const worker = createWorker({ analyze: async () => { calls++; throw new Error('Unexpected provider call'); } }); const cases = [[request({ repository: 'acme/demo' }, { Origin: 'https://evil.example' }), {}, 403], [request({ repository: 'acme/demo' }), { GENIUS_ACCESS_TOKEN: 'private-instance-placeholder' }, 401], [request({ repository: 'acme/demo', maxFiles: 41 }), {}, 400], [request('{bad json'), {}, 400], [request({ repository: 'x'.repeat(22000) }), {}, 413]]; for (const [input, env, status] of cases) { const response = await worker.fetch(input, env); assert.equal(response.status, status); assert.ok((await response.json()).error); } assert.equal(calls, 0); const health = await (await worker.fetch(new Request('https://diagram.example/api/health'), {})).json(); assert.equal(health.limits.maxFiles, 40); assert.equal(health.aiAvailable, false); }); // Reject invalid requests before they consume GitHub or model resources.
test('Mermaid role colors are distinct, labeled, and preserve author-provided styles', () => { const expected = { 'src/main.cpp': 'entry', 'src/helper.js': 'source', 'public/panel.css': 'ui', 'include/sensor.h': 'hardware', 'config/board_config.h': 'config', 'README.md': 'document', 'tests/main.test.js': 'test', 'src/safety_manager.cpp': 'safety' }; for (const [path, role] of Object.entries(expected)) assert.equal(fileRole(path), role); assert.equal(new Set(Object.values(ROLE_PALETTE).map(item => item.stroke)).size, 8); const source = 'flowchart TD\nA --> B\nclassDef power fill:#173d2c,stroke:#79d99b\n'; const samples = [...files, { path: 'docs/wiring.md', content: `\u0060\u0060\u0060mermaid\n${source}\u0060\u0060\u0060`, sha: commitSHA, size: 100 }]; const result = analyzeSnapshot({ repo: 'demo', fullName: 'acme/demo', scope: '', entries }, samples, { readFiles: samples.length, eligibleFiles: samples.length, listedFiles: samples.length, skipped: [] }); assert.equal(result.documented.at(-1).source, source); for (const item of result.diagrams.legend) assert.ok(result.diagrams.architecture.includes(`classDef ${item.role} fill:${item.fill},stroke:${item.stroke}`)); }); // Validate color meaning and authored-diagram fidelity as separate concerns.
