// Project: Git Architecture Diagram | Component: Portable production build | Author: Amine Saoud ibn al-Bashir.
import { build } from 'esbuild'; // Bundle the existing browser modules and the small hosted Worker.
import { mkdir, rm, copyFile, writeFile, readdir, cp } from 'node:fs/promises'; // Recreate only generated output, never source or credentials.
import path from 'node:path'; // Resolve allowlisted browser vendor aliases to their installed distributions.
import { fileURLToPath } from 'node:url'; // Run reproducibly from the repository root.
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..'); process.chdir(root); // Keep builds independent of the caller's working directory.
await rm('dist', { recursive: true, force: true }); await mkdir('dist/client', { recursive: true }); await mkdir('dist/server', { recursive: true }); // Replace disposable generated output in its dedicated directory.
const aliases = { '/vendor/mermaid/mermaid.esm.min.mjs': 'node_modules/mermaid/dist/mermaid.esm.min.mjs', '/vendor/dompurify/purify.es.mjs': 'node_modules/dompurify/dist/purify.es.mjs', '/vendor/marked/marked.esm.js': 'node_modules/marked/lib/marked.esm.js', '/vendor/fflate/browser.js': 'node_modules/fflate/esm/browser.js', '/shared/evidence.mjs': 'src/evidence.mjs' }; // Bundle the exact local dependencies used by the development server.
await build({ entryPoints: ['public/app.js'], outdir: 'dist/client', bundle: true, format: 'esm', splitting: true, platform: 'browser', target: 'es2022', minify: true, chunkNames: 'chunks/[name]-[hash]', plugins: [{ name: 'local-browser-modules', setup(builder) { builder.onResolve({ filter: /^\/(?:vendor|shared)\// }, args => aliases[args.path] ? { path: path.join(root, aliases[args.path]) } : { errors: [{ text: `Unknown local module: ${args.path}` }] }); } }] }); // Produce same-origin assets with Mermaid's diagrams split into lazy chunks.
for (const name of ['index.html', 'styles.css', 'favicon.svg']) await copyFile(`public/${name}`, `dist/client/${name}`); await cp('public/assets', 'dist/client/assets', { recursive: true }); await mkdir('dist/client/fonts', { recursive: true }); for (const name of await readdir('public/fonts')) await copyFile(`public/fonts/${name}`, `dist/client/fonts/${name}`); // Ship the self-hosted interface fonts, their license, and the local brand images. // Package the real interface without including environment files or source reports.
await build({ entryPoints: ['worker.mjs'], outfile: 'dist/server/index.js', bundle: true, format: 'esm', platform: 'neutral', target: 'es2022', external: ['node:*'], minify: false }); // Emit a Workers-compatible ESM fetch handler with explicit Node compatibility imports.
const config = { name: 'git-architecture-diagram', main: 'index.js', compatibility_date: '2026-09-01', compatibility_flags: ['nodejs_compat'], assets: { directory: '../client', binding: 'ASSETS', run_worker_first: true } }; // Declare only portable runtime compatibility and the static asset binding.
await writeFile('dist/server/wrangler.json', JSON.stringify(config, null, 2) + '\n'); // Publish the Worker and its local assets together.
console.log('Built the Git Architecture Diagram browser workspace and hosted Worker.'); // Report the actual completed build.
