// Fixed-endpoint text-model adapters; caller credentials never choose an arbitrary destination.
import { AppError } from './github.mjs'; // Reuse safe, bounded errors that do not echo provider payloads.
import { PROVIDERS } from '../public/providers.js'; // Keep the UI and server provider identities aligned.
export { PROVIDERS }; // Expose the same catalog to analysis orchestration.
export function providerRequest(provider, { apiKey, model, instructions, payload, schema }) { // Build one provider-specific request without performing network operations.
  if (!Object.hasOwn(PROVIDERS, provider)) throw new AppError(400, 'Choose OpenAI, Claude, Gemini, or Kimi in Settings.'); // Reject unknown provider names and object prototype keys.
  const headers = { 'Content-Type': 'application/json' }; const input = JSON.stringify(payload); // Serialize only the bounded source context.
  if (provider === 'openai') return { url: 'https://api.openai.com/v1/responses', headers: { ...headers, Authorization: `Bearer ${apiKey}` }, body: { model, store: false, instructions, input, max_output_tokens: 6000, text: { format: { type: 'json_schema', name: 'genius_architecture', strict: true, schema } } } }; // Request strict JSON with no stored response.
  if (provider === 'anthropic') return { url: 'https://api.anthropic.com/v1/messages', headers: { ...headers, 'x-api-key': apiKey, 'anthropic-version': '2023-06-01' }, body: { model, max_tokens: 6000, system: instructions, messages: [{ role: 'user', content: input }], output_config: { format: { type: 'json_schema', schema } } } }; // Use the current non-beta structured output field.
  if (provider === 'gemini') return { url: `https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`, headers: { ...headers, 'x-goog-api-key': apiKey }, body: { systemInstruction: { parts: [{ text: instructions }] }, contents: [{ role: 'user', parts: [{ text: input }] }], generationConfig: { maxOutputTokens: 6000, responseFormat: { text: { mimeType: 'APPLICATION_JSON', schema } } } } }; // Keep the key out of the URL and use the current response-format contract.
  return { url: 'https://api.moonshot.ai/v1/chat/completions', headers: { ...headers, Authorization: `Bearer ${apiKey}` }, body: { model, messages: [{ role: 'system', content: instructions }, { role: 'user', content: input }], max_tokens: 6000, ...(model.startsWith('kimi-k3') ? { reasoning_effort: 'low' } : {}), response_format: { type: 'json_schema', json_schema: { name: 'genius_architecture', strict: true, schema } } } }; // Bound K3 reasoning for interactive explanations.
} // End request adaptation.
export function providerOutput(provider, data) { // Normalize final text while rejecting refusals and truncated output.
  const incomplete = () => { throw new AppError(502, 'The AI response was refused or incomplete. The structural report remains available.'); }; // Avoid displaying partial output as a completed report.
  if (provider === 'openai') { const content = (data.output || []).flatMap(item => item.content || []); if (data.status === 'incomplete' || data.status === 'failed' || content.some(item => item.type === 'refusal')) incomplete(); return { text: content.filter(item => item.type === 'output_text').map(item => item.text).join(''), model: data.model, usage: data.usage }; } // Inspect all Responses output blocks, not just the first item.
  if (provider === 'anthropic') { if (['refusal', 'max_tokens'].includes(data.stop_reason)) incomplete(); return { text: (data.content || []).filter(item => item.type === 'text').map(item => item.text).join(''), model: data.model, usage: data.usage }; } // Ignore non-text Anthropic content blocks.
  if (provider === 'gemini') { const candidate = data.candidates?.[0]; if (!candidate || data.promptFeedback?.blockReason || candidate.finishReason !== 'STOP') incomplete(); return { text: (candidate.content?.parts || []).filter(item => !item.thought && typeof item.text === 'string').map(item => item.text).join(''), model: data.modelVersion, usage: data.usageMetadata }; } // Never expose thought parts as final report content.
  const choice = data.choices?.[0]; if (!choice || choice.finish_reason !== 'stop') incomplete(); return { text: choice.message?.content || '', model: data.model, usage: data.usage }; // Keep Kimi reasoning_content separate from the final answer.
} // End output adaptation.
